// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI agent that explains a concept or question in a clear, concise manner suitable for students.
 *
 * - explainConcept - A function that handles the concept explanation process.
 * - ExplainConceptInput - The input type for the explainConcept function.
 * - ExplainConceptOutput - The return type for the explainConcept function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainConceptInputSchema = z.object({
  concept: z.string().describe('The concept or question to be explained.'),
  gradeLevel: z.number().describe('The grade level for which the explanation should be tailored.'),
});
export type ExplainConceptInput = z.infer<typeof ExplainConceptInputSchema>;

const ExplainConceptOutputSchema = z.object({
  explanation: z.string().describe('A clear and concise explanation of the concept suitable for the specified grade level.'),
});
export type ExplainConceptOutput = z.infer<typeof ExplainConceptOutputSchema>;

export async function explainConcept(input: ExplainConceptInput): Promise<ExplainConceptOutput> {
  return explainConceptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainConceptPrompt',
  input: {schema: ExplainConceptInputSchema},
  output: {schema: ExplainConceptOutputSchema},
  prompt: `You are an expert teacher skilled at explaining complex concepts to students.

  Explain the following concept or question to a student at the specified grade level.

  Concept: {{{concept}}}
  Grade Level: {{{gradeLevel}}}

  Provide a clear, concise, and easy-to-understand explanation.
  `,
});

const explainConceptFlow = ai.defineFlow(
  {
    name: 'explainConceptFlow',
    inputSchema: ExplainConceptInputSchema,
    outputSchema: ExplainConceptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
