
export const ela10Curriculum = {
    units: {
        "Unit 1: Truth and Perspective": {
            topics: {
                "Point of View and Reliability": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: What is Truth?", standard: "9-10SL1" },
                        { title: "Day 2: Engage: A Question of Truth", standard: "9-10W4" },
                        { title: "Day 3: Defining Point of View and Narrator Reliability", standard: "9-10R6" },
                        { title: "Day 4: Anchor Text Introduction", standard: "9-10R2" },
                        { title: "Day 5: Reading and First Impressions", standard: "9-10R1" },
                        { title: "Day 6: Analyzing Diction and Tone", standard: "9-10R4" },
                        { title: "Day 7: Tracking the Narrative", standard: "9-10R3" },
                        { title: "Day 8: Character Motivation", standard: "9-10R3" },
                        { title: "Day 9: Group Discussion: Is the Narrator Trustworthy?", standard: "9-10SL1c" },
                        { title: "Day 10: Writing Workshop: Character Voice Journal", standard: "9-10W3" },
                        { title: "Day 11: How Perspective Shapes Plot", standard: "9-10R6" },
                        { title: "Day 12: The Impact of an Unreliable Narrator", standard: "9-10R6" },
                        { title: "Day 13: Reading and Analyzing a Key Scene", standard: "9-10R3" },
                        { title: "Day 14: Socratic Seminar Preparation", standard: "9-10SL1a" },
                        { title: "Day 15: Socratic Seminar", standard: "9-10SL1" },
                        { title: "Day 16: Connecting to Other Perspectives", standard: "9-10R9" },
                        { title: "Day 17: Comparative Analysis", standard: "9-10R7" },
                        { title: "Day 18: Introduction to the Analytical Essay", standard: "9-10W2" },
                        { title: "Day 19: Essay Workshop: Developing a Thesis", standard: "9-10W2a" },
                        { title: "Day 20: Essay Workshop: Gathering Evidence", standard: "9-10W5" },
                        { title: "Day 21: Elaboration: Rewriting a Scene", standard: "9-10W3" },
                        { title: "Day 22: Creative Writing Workshop: Capturing a New Voice", standard: "9-10W3d" },
                        { title: "Day 23: Peer Review: Creative Scene", standard: "9-10W3" },
                        { title: "Day 24: Sharing Rewritten Scenes", standard: "9-10SL4" },
                        { title: "Day 25: Connecting Creative and Analytical Writing", standard: "9-10W4" },
                        { title: "Day 26: Essay Workshop: Outlining", standard: "9-10W2a" },
                        { title: "Day 27: Drafting the Essay: Introduction and Body", standard: "9-10W2" },
                        { title: "Day 28: Drafting the Essay: Conclusion", standard: "9-10W2e" },
                        { title: "Day 29: Figurative Language and Nuance", standard: "9-10L5" },
                        { title: "Day 30: Revising for Argument", standard: "9-10W2" },
                        { title: "Day 31: Revising for Clarity and Style", standard: "9-10W2" },
                        { title: "Day 32: Peer Review Workshop: Full Essay", standard: "9-10W2" },
                        { title: "Day 33: Final Revisions", standard: "9-10L1" },
                        { title: "Day 34: Editing and Proofreading", standard: "9-10L2" },
                        { title: "Day 35: Final Essay Submission", standard: "9-10W2" },
                        { title: "Day 36: Introduction to a New Text with Multiple Perspectives", standard: "9-10R6" },
                        { title: "Day 37: Comparing Narrative Structures", standard: "9-10R5" },
                        { title: "Day 38: Evaluating a Speaker's Perspective", standard: "9-10SL3" },
                        { title: "Day 39: Discussion: Truth in Non-Fiction", standard: "9-10SL1" },
                        { title: "Day 40: Debate: Is Objective Truth Possible?", standard: "9-10SL1c" },
                        { title: "Day 41: Creative Response Project Intro", standard: "9-10W4" },
                        { title: "Day 42: Creative Project Work Day", standard: "9-10W4" },
                        { title: "Day 43: Creative Project Work Day", standard: "9-10W4" },
                        { title: "Day 44: Project Showcase", standard: "9-10SL4" },
                        { title: "Day 45: Unit Reflection", standard: "9-10W4" }
                    ]
                }
            }
        },
        "Unit 2: Utopia and Dystopia": {
            topics: {
                "Analyzing Dystopian Societies": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: The Concept of Utopia", standard: "9-10R2" },
                        { title: "Day 2: Engage: Designing a Perfect World", standard: "9-10W3" },
                        { title: "Day 3: Presenting Utopias", standard: "9-10SL4" },
                        { title: "Day 4: Characteristics of Dystopian Fiction", standard: "9-10R5" },
                        { title: "Day 5: Anchor Text Introduction", standard: "9-10R2" },
                        { title: "Day 6: World-Building Analysis", standard: "9-10R3" },
                        { title: "Day 7: Analyzing Dystopian Control", standard: "9-10R3" },
                        { title: "Day 8: The Dystopian Protagonist", standard: "9-10R3" },
                        { title: "Day 9: Reading and Discussion", standard: "9-10SL1" },
                        { title: "Day 10: Writing Workshop: World-Building Paragraph", standard: "9-10W2" },
                        { title: "Day 11: Thematic Development: Conformity vs. Individuality", standard: "9-10R2" },
                        { title: "Day 12: Analyzing Propaganda", standard: "9-10R8" },
                        { title: "Day 13: Symbolism in Dystopian Literature", standard: "9-10R4" },
                        { title: "Day 14: Reading and Analyzing the Climax", standard: "9-10R3" },
                        { title: "Day 15: Socratic Seminar", standard: "9-10SL1" },
                        { title: "Day 16: Connecting to the Real World: Research Mini-Project", standard: "9-10W6" },
                        { title: "Day 17: Research Day", standard: "9-10W7" },
                        { title: "Day 18: Making Connections", standard: "9-10R9" },
                        { title: "Day 19: Sharing Connections", standard: "9-10SL4" },
                        { title: "Day 20: Summative Essay Introduction", standard: "9-10W2" },
                        { title: "Day 21: Essay Workshop: Thesis Development", standard: "9-10W2a" },
                        { title: "Day 22: Essay Workshop: Gathering Evidence", standard: "9-10W5" },
                        { title: "Day 23: Essay Workshop: Outlining", standard: "9-10W2a" },
                        { title: "Day 24: Drafting the Explanatory Essay", standard: "9-10W2" },
                        { title: "Day 25: Peer Review Workshop", standard: "9-10W2" },
                        { title: "Day 26: Revising the Essay", standard: "9-10W2" },
                        { title: "Day 27: Vocabulary and Precise Language", standard: "9-10L6" },
                        { title: "Day 28: Finalizing the Explanatory Essay", standard: "9-10L2" },
                        { title: "Day 29: Elaboration: Dystopia on Screen Intro", standard: "9-10R7" },
                        { title: "Day 30: Film Viewing Day 1", standard: "9-10R7" },
                        { title: "Day 31: Film Viewing Day 2", standard: "9-10R7" },
                        { title: "Day 32: Comparative Analysis: Book vs. Film", standard: "9-10R7" },
                        { title: "Day 33: Discussion: Analyzing Adaptation Choices", standard: "9-10SL1" },
                        { title: "Day 34: Creative Response Intro: Your Dystopia", standard: "9-10W3" },
                        { title: "Day 35: Creative Project: World-Building", standard: "9-10W3b" },
                        { title: "Day 36: Creative Project: The Protagonist", standard: "9-10W3a" },
                        { title: "Day 37: Creative Project: Writing a Scene", standard: "9-10W3c" },
                        { title: "Day 38: Creative Project Workshop", standard: "9-10W3" },
                        { title: "Day 39: Finalizing Creative Projects", standard: "9-10W3" },
                        { title: "Day 40: Submit Explanatory Essay", standard: "9-10W2" },
                        { title: "Day 41: Dystopian Showcase Day 1", standard: "9-10SL4" },
                        { title: "Day 42: Dystopian Showcase Day 2", standard: "9-10SL4" },
                        { title: "Day 43: Unit Closure Discussion", standard: "9-10SL1d" },
                        { title: "Day 44: Final Thematic Connection", standard: "9-10R9" },
                        { title: "Day 45: Unit Reflection", standard: "9-10W4" }
                    ]
                }
            }
        },
        "Unit 3: Foundational Myths and Modern Meanings": {
            topics: {
                "Exploring Archetypes and Allusions": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: What is a Myth?", standard: "9-10R2" },
                        { title: "Day 2: Engage: Modern Heroes and Monsters", standard: "9-10SL1" },
                        { title: "Day 3: The Hero's Journey", standard: "9-10R3" },
                        { title: "Day 4: Reading Foundational Myths 1: Creation Myths", standard: "9-10R2" },
                        { title: "Day 5: Reading Foundational Myths 2: Hero Myths", standard: "9-10R2" },
                        { title: "Day 6: Character Archetypes", standard: "9-10R3" },
                        { title: "Day 7: Anchor Text Introduction", standard: "9-10R9" },
                        { title: "Day 8: Identifying Mythological Parallels", standard: "9-10R9" },
                        { title: "Day 9: Analyzing Allusions", standard: "9-10R4" },
                        { title: "Day 10: Reading the Anchor Text", standard: "9-10R1" },
                        { title: "Day 11: Transformation of Character", standard: "9-10R3" },
                        { title: "Day 12: Transformation of Theme", standard: "9-10R2" },
                        { title: "Day 13: Discussion: Why Adapt Myths?", standard: "9-10SL1" },
                        { title: "Day 14: Reading and Discussion", standard: "9-10SL1" },
                        { title: "Day 15: Socratic Seminar", standard: "9-10SL1d" },
                        { title: "Day 16: Myths Across Media", standard: "9-10R7" },
                        { title: "Day 17: Comparative Analysis: Different Media", standard: "9-10R7" },
                        { title: "Day 18: Creative Response Project Introduction", standard: "9-10W4" },
                        { title: "Day 19: Brainstorming for Creative Adaptation", standard: "9-10W4" },
                        { title: "Day 20: Project Planning", standard: "9-10W4" },
                        { title: "Day 21: Creative Writing Workshop: Narrative", standard: "9-10W3" },
                        { title: "Day 22: Creative Writing Workshop: Poetry", standard: "9-10W4" },
                        { title: "Day 23: Creative Project Work Day", standard: "9-10W4" },
                        { title: "Day 24: Peer Review Workshop", standard: "9-10W4" },
                        { title: "Day 25: Revising Creative Projects", standard: "9-10W4" },
                        { title: "Day 26: Analytical Essay Introduction", standard: "9-10W2" },
                        { title: "Day 27: Essay Workshop: Comparative Thesis", standard: "9-10W2a" },
                        { title: "Day 28: Essay Workshop: Structuring a Comparative Essay", standard: "9-10W2a" },
                        { title: "Day 29: Essay Workshop: Gathering Evidence", standard: "9-10W5" },
                        { title: "Day 30: Drafting the Comparative Essay", standard: "9-10W2" },
                        { title: "Day 31: Finalizing Creative Projects", standard: "9-10W4" },
                        { title: "Day 32: Peer Review: Comparative Essay", standard: "9-10W2" },
                        { title: "Day 33: Revising the Comparative Essay", standard: "9-10W2" },
                        { title: "Day 34: Language Workshop: Academic Vocabulary", standard: "9-10L6" },
                        { title: "Day 35: Editing and Proofreading", standard: "9-10L2" },
                        { title: "Day 36: Submit Comparative Essay", standard: "9-10W2" },
                        { title: "Day 37: Presentation Skills Workshop", standard: "9-10SL4" },
                        { title: "Day 38: Presentation Preparation", standard: "9-10SL5" },
                        { title: "Day 39: Mythology Showcase Day 1", standard: "9-10SL4" },
                        { title: "Day 40: Mythology Showcase Day 2", standard: "9-10SL4" },
                        { title: "Day 41: Mythology Showcase Day 3", standard: "9-10SL4" },
                        { title: "Day 42: Gallery Walk", standard: "9-10SL2" },
                        { title: "Day 43: Unit Closure Discussion", standard: "9-10SL1d" },
                        { title: "Day 44: Connecting to Personal Experience", standard: "9-10R9" },
                        { title: "Day 45: Unit Reflection", standard: "9-10W4" }
                    ]
                }
            }
        },
        "Unit 4: The Language of Poetry": {
            topics: {
                "Sound and Sense in Poetry": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: What is Poetry?", standard: "9-10R5" },
                        { title: "Day 2: Engage: Hearing the Music in Language", standard: "9-10L5" },
                        { title: "Day 3: Figurative Language 1: Simile and Metaphor", standard: "9-10R4" },
                        { title: "Day 4: Figurative Language 2: Personification and Imagery", standard: "9-10R4" },
                        { title: "Day 5: Sound Devices 1: Alliteration and Assonance", standard: "9-10R4" },
                        { title: "Day 6: Sound Devices 2: Rhyme and Rhythm", standard: "9-10R5" },
                        { title: "Day 7: Connotation and Denotation", standard: "9-10L5b" },
                        { title: "Day 8: Close Reading a Poem: TP-CASTT", standard: "9-10R1" },
                        { title: "Day 9: Applying TP-CASTT", standard: "9-10R1" },
                        { title: "Day 10: Writing Workshop: Short Analysis", standard: "9-10W2" },
                        { title: "Day 11: Poetic Structure 1: The Stanza and the Line", standard: "9-10R5" },
                        { title: "Day 12: Poetic Structure 2: Fixed Forms (The Sonnet)", standard: "9-10R5" },
                        { title: "Day 13: Poetic Structure 3: Free Verse", standard: "9-10R5" },
                        { title: "Day 14: Comparing Forms", standard: "9-10R5" },
                        { title: "Day 15: Discussion: Form and Freedom", standard: "9-10SL1" },
                        { title: "Day 16: Creative Writing Intro: Poetry Imitation", standard: "9-10W4" },
                        { title: "Day 17: Imitation Workshop 1: Sound", standard: "9-10W4" },
                        { title: "Day 18: Imitation Workshop 2: Figurative Language", standard: "9-10W4" },
                        { title: "Day 19: Imitation Workshop 3: Form", standard: "9-10W4" },
                        { title: "Day 20: Peer Review: Imitation Poems", standard: "9-10W4" },
                        { title: "Day 21: Creative Writing: Personal Experience", standard: "9-10W3" },
                        { title: "Day 22: Drafting Workshop 1: Getting Ideas Down", standard: "9-10W3" },
                        { title: "Day 23: Drafting Workshop 2: Shaping the Poem", standard: "9-10W3" },
                        { title: "Day 24: Revision Workshop: The Power of the Verb", standard: "9-10L3" },
                        { title: "Day 25: Revision Workshop: Cutting Clutter", standard: "9-10L3" },
                        { title: "Day 26: Poetry Peer Review", standard: "9-10W3" },
                        { title: "Day 27: Finalizing Personal Poems", standard: "9-10W3" },
                        { title: "Day 28: Poetry Anthology Project Introduction", standard: "9-10W6" },
                        { title: "Day 29: Selecting Poems for Anthology", standard: "9-10W7" },
                        { title: "Day 30: Writing Analyses for Anthology", standard: "9-10W2" },
                        { title: "Day 31: Anthology Work Day", standard: "9-10W2" },
                        { title: "Day 32: Anthology Peer Review", standard: "9-10W2" },
                        { title: "Day 33: Finalizing Anthologies", standard: "9-10W2" },
                        { title: "Day 34: Performance Poetry Intro", standard: "9-10SL4" },
                        { title: "Day 35: Analyzing a Spoken Word Performance", standard: "9-10SL3" },
                        { title: "Day 36: Preparing for a Poetry Slam", standard: "9-10SL4" },
                        { title: "Day 37: Performance Workshop", standard: "9-10SL6" },
                        { title: "Day 38: Presentation Visuals", standard: "9-10SL5" },
                        { title: "Day 39: Poetry Slam Day 1", standard: "9-10SL4" },
                        { title: "Day 40: Poetry Slam Day 2", standard: "9-10SL4" },
                        { title: "Day 41: Poetry Slam Day 3", standard: "9-10SL4" },
                        { title: "Day 42: Submit Poetry Anthology", standard: "9-10W2" },
                        { title: "Day 43: Found Poetry Workshop", standard: "9-10W4" },
                        { title: "Day 44: Unit Closure Discussion", standard: "9-10SL1d" },
                        { title: "Day 45: Unit Reflection", standard: "9-10W4" }
                    ]
                }
            }
        }
    }
};
