
export const ela12Curriculum = {
    units: {
      "Unit 1: Choice and Consequence": {
          topics: {
              "Analyzing Complex Characters": {
                  lessons: [
                      { title: "Day 1: Unit Introduction: Fate and Free Will", standard: "11-12R2" },
                      { title: "Day 2: Engage: A Moral Dilemma", standard: "11-12SL1" },
                      { title: "Day 3: Anchor Text Introduction", standard: "11-12R2" },
                      { title: "Day 4: Reading and Identifying Core Conflicts", standard: "11-12R3" },
                      { title: "Day 5: Analyzing Character Motivation", standard: "11-12R3" },
                      { title: "Day 6: Moral Ambiguity", standard: "11-12R1" },
                      { title: "Day 7: Reading and Discussion", standard: "11-12SL1" },
                      { title: "Day 8: Choice-and-Consequence Mapping", standard: "11-12R3" },
                      { title: "Day 9: Thematic Development: Guilt and Responsibility", standard: "11-12R2" },
                      { title: "Day 10: Socratic Seminar", standard: "11-12SL1" },
                      { title: "Day 11: Analyzing Structure and Pacing", standard: "11-12R5" },
                      { title: "Day 12: Literary Theory 1: Psychoanalytic Lens", standard: "11-12R8" },
                      { title: "Day 13: Literary Theory 2: Existentialist Lens", standard: "11-12R8" },
                      { title: "Day 14: Applying Critical Lenses", standard: "11-12R8" },
                      { title: "Day 15: Reading and Discussion to Conclusion", standard: "11-12R1" },
                      { title: "Day 16: Debate: A Character on Trial", standard: "11-12SL1" },
                      { title: "Day 17: Introduction to the Literary Argument Essay", standard: "11-12W1" },
                      { title: "Day 18: Essay Workshop: Complex Thesis", standard: "11-12W1a" },
                      { title: "Day 19: Essay Workshop: Using Ambiguous Evidence", standard: "11-12W1b" },
                      { title: "Day 20: Essay Workshop: Outlining", standard: "11-12W1a" },
                      { title: "Day 21: Drafting Workshop: Introduction", standard: "11-12W1a" },
                      { title: "Day 22: Drafting Workshop: Body Paragraphs", standard: "11-12W1b" },
                      { title: "Day 23: Language Workshop: Syntax for Effect", standard: "11-12L3a" },
                      { title: "Day 24: Drafting Workshop: Conclusion", standard: "11-12W1e" },
                      { title: "Day 25: Self-Revision Workshop", standard: "11-12W1" },
                      { title: "Day 26: Peer Review Workshop", standard: "11-12W1" },
                      { title: "Day 27: Teacher-Student Conferences", standard: "11-12SL1" },
                      { title: "Day 28: Revision Planning", standard: "11-12W1" },
                      { title: "Day 29: Revising the Essay", standard: "11-12W1" },
                      { title: "Day 30: Editing and Proofreading", standard: "11-12L1" },
                      { title: "Day 31: Final Essay Submission", standard: "11-12W1" },
                      { title: "Day 32: Elaboration: Philosophical Chairs", standard: "11-12SL1d" },
                      { title: "Day 33: Debate Reflection", standard: "11-12W4" },
                      { title: "Day 34: Connecting to Film", standard: "11-12R7" },
                      { title: "Day 35: Connecting to Personal Experience", standard: "11-12R9" },
                      { title: "Day 36: Introduction to the Final Project", standard: "11-12W6" },
                      { title: "Day 37: Project Proposal Workshop", standard: "11-12W6" },
                      { title: "Day 38: Project Work Day", standard: "11-12W6" },
                      { title: "Day 39: Project Work Day", standard: "11-12W6" },
                      { title: "Day 40: Project Work Day", standard: "11-12W6" },
                      { title: "Day 41: Final Project Presentations Day 1", standard: "11-12SL4" },
                      { title: "Day 42: Final Project Presentations Day 2", standard: "11-12SL4" },
                      { title: "Day 43: Unit Closure Discussion", standard: "11-12SL1d" },
                      { title: "Day 44: Portfolio Selection", standard: "11-12W6" },
                      { title: "Day 45: Unit Reflection", standard: "11-12W4" }
                  ]
              }
          }
      },
      "Unit 2: Reading the World": {
          topics: {
              "Exploring Global Literature": {
                  lessons: [
                      { title: "Day 1: Unit Introduction: Mapping Our Literary Worlds", standard: "11-12R9" },
                      { title: "Day 2: Engage: Universal Themes", standard: "11-12R2" },
                      { title: "Day 3: Anchor Text Introduction", standard: "11-12R2" },
                      { title: "Day 4: Context Workshop: Researching the Culture", standard: "11-12W6" },
                      { title: "Day 5: Reading and Annotating for Cultural Perspective", standard: "11-12R6" },
                      { title: "Day 6: Discussing Initial Readings", standard: "11-12SL1" },
                      { title: "Day 7: Reading the Anchor Text", standard: "11-12R1" },
                      { title: "Day 8: Analyzing Character through a Cultural Lens", standard: "11-12R3" },
                      { title: "Day 9: Thematic Development", standard: "11-12R2" },
                      { title: "Day 10: Writing Workshop: Cultural Analysis", standard: "11-12W2" },
                      { title: "Day 11: Continued Reading and Discussion", standard: "11-12SL1" },
                      { title: "Day 12: Author's Purpose and Message", standard: "11-12R6" },
                      { title: "Day 13: Making Connections to Personal Experience", standard: "11-12R9" },
                      { title: "Day 14: Socratic Seminar Preparation", standard: "11-12SL1a" },
                      { title: "Day 15: Socratic Seminar", standard: "11-12SL1" },
                      { title: "Day 16: Introduction to the Explanatory Essay", standard: "11-12W2" },
                      { title: "Day 17: Essay Workshop: Thesis Development", standard: "11-12W2a" },
                      { title: "Day 18: Essay Workshop: Gathering Evidence", standard: "11-12W5" },
                      { title: "Day 19: Essay Workshop: Outlining", standard: "11-12W2a" },
                      { title: "Day 20: Drafting the Essay", standard: "11-12W2" },
                      { title: "Day 21: Peer Review Workshop", standard: "11-12W2" },
                      { title: "Day 22: Revising the Essay", standard: "11-12W2" },
                      { title: "Day 23: Language Workshop: Vocabulary", standard: "11-12L6" },
                      { title: "Day 24: Finalizing the Explanatory Essay", standard: "11-12L2" },
                      { title: "Day 25: Explanatory Essay Due", standard: "11-12W2" },
                      { title: "Day 26: Elaboration: Exploring World Literature through Poetry", standard: "11-12R9" },
                      { title: "Day 27: Discussion: Universal vs. Culturally Specific", standard: "11-12SL1" },
                      { title: "Day 28: Creative Response Project Introduction", standard: "11-12W4" },
                      { title: "Day 29: Project Brainstorming and Planning", standard: "11-12W4" },
                      { title: "Day 30: Project Work Day 1", standard: "11-12W4" },
                      { title: "Day 31: Project Work Day 2", standard: "11-12W4" },
                      { title: "Day 32: Project Work Day 3", standard: "11-12W4" },
                      { title: "Day 33: Connecting to Other Media: World Cinema", standard: "11-12R7" },
                      { title: "Day 34: Comparative Discussion: Literature and Film", standard: "11-12SL1" },
                      { title: "Day 35: Guest Speaker or Virtual Tour", standard: "11-12SL2" },
                      { title: "Day 36: Student-Led Presentations: Cultural Spotlight", standard: "11-12SL4" },
                      { title: "Day 37: Presentations Day 1", standard: "11-12SL4" },
                      { title: "Day 38: Presentations Day 2", standard: "11-12SL4" },
                      { title: "Day 39: Synthesizing Across Presentations", standard: "11-12SL2" },
                      { title: "Day 40: Showcase of Creative Projects", standard: "11-12SL5" },
                      { title: "Day 41: Artist's Statement Workshop", standard: "11-12W2" },
                      { title: "Day 42: Unit Closure Discussion", standard: "11-12SL1d" },
                      { title: "Day 43: Acquiring Academic Vocabulary", standard: "11-12L6" },
                      { title: "Day 44: Portfolio Curation", standard: "11-12W6" },
                      { title: "Day 45: Final Unit Reflection", standard: "11-12W4" }
                  ]
              }
          }
      },
      "Unit 3: Satire and Social Critique": {
          topics: {
              "Understanding Satire": {
                  lessons: [
                      { title: "Day 1: Unit Introduction: The Power of Humor", standard: "11-12R6" },
                      { title: "Day 2: Engage: Analyzing Contemporary Satire", standard: "11-12R7" },
                      { title: "Day 3: The Satirist's Toolkit", standard: "11-12L5a" },
                      { title: "Day 4: Anchor Text Introduction", standard: "11-12R2" },
                      { title: "Day 5: Reading and Deconstructing the Anchor Text", standard: "11-12R1" },
                      { title: "Day 6: Analyzing Ironic Tone", standard: "11-12R4" },
                      { title: "Day 7: Hyperbole and Understatement", standard: "11-12L5a" },
                      { title: "Day 8: Delineating the Satirical Argument", standard: "11-12R8" },
                      { title: "Day 9: Discussion: The Satirical Target", standard: "11-12SL1" },
                      { title: "Day 10: Writing Workshop: Satirical Analysis", standard: "11-12W2" },
                      { title: "Day 11: Continued Reading and Analysis", standard: "11-12R1" },
                      { title: "Day 12: The Role of Logic in Satire", standard: "11-12R8" },
                      { title: "Day 13: Evaluating the Argument", standard: "11-12R8" },
                      { title: "Day 14: Socratic Seminar", standard: "11-12SL1" },
                      { title: "Day 15: Introduction to the Explanatory Essay", standard: "11-12W2" },
                      { title: "Day 16: Essay Workshop: Thesis Development", standard: "11-12W2a" },
                      { title: "Day 17: Essay Workshop: Gathering Evidence", standard: "11-12W5" },
                      { title: "Day 18: Essay Workshop: Outlining", standard: "11-12W2a" },
                      { title: "Day 19: Drafting the Essay", standard: "11-12W2" },
                      { title: "Day 20: Peer Review and Revision", standard: "11-12W2" },
                      { title: "Day 21: Elaboration: Satire in Different Media", standard: "11-12R7" },
                      { title: "Day 22: Analyzing Political Cartoons", standard: "11-12R7" },
                      { title: "Day 23: Evaluating a Speaker's Satirical Argument", standard: "11-12SL3" },
                      { title: "Day 24: Discussion: The Motives of Satire", standard: "11-12SL1" },
                      { title: "Day 25: Introduction to the Creative Satire Project", standard: "11-12W4" },
                      { title: "Day 26: Brainstorming Topics for Satire", standard: "11-12W3" },
                      { title: "Day 27: Choosing a Satirical Mode", standard: "11-12W3" },
                      { title: "Day 28: Creative Project Work Day: Drafting", standard: "11-12W3" },
                      { title: "Day 29: Workshop: Creating an Ironic Persona", standard: "11-12W3a" },
                      { title: "Day 30: Creative Project Peer Review", standard: "11-12W3" },
                      { title: "Day 31: Revising Creative Projects", standard: "11-12W3" },
                      { title: "Day 32: Finalizing Creative Projects", standard: "11-12W3" },
                      { title: "Day 33: Finalizing the Analytical Essay", standard: "11-12L1" },
                      { title: "Day 34: Essay Submission", standard: "11-12W2" },
                      { title: "Day 35: Preparing for the Satire Showcase", standard: "11-12SL4" },
                      { title: "Day 36: Presentation Workshop: Using Visuals", standard: "11-12SL5" },
                      { title: "Day 37: Satire Showcase Day 1", standard: "11-12SL4" },
                      { title: "Day 38: Satire Showcase Day 2", standard: "11-12SL4" },
                      { title: "Day 39: Satire Showcase Day 3", standard: "11-12SL4" },
                      { title: "Day 40: Audience Response and Discussion", standard: "11-12SL1" },
                      { title: "Day 41: The Limits and Dangers of Satire", standard: "11-12SL3" },
                      { title: "Day 42: Debate: The Responsibility of the Satirist", standard: "11-12SL1c" },
                      { title: "Day 43: Final Text Analysis", standard: "11-12R8" },
                      { title: "Day 44: Portfolio Selection and Reflection", standard: "11-12W6" },
                      { title: "Day 45: Unit Reflection", standard: "11-12W4" }
                  ]
              }
          }
      },
      "Unit 4: Crafting the Future: College and Career Writing": {
          topics: {
              "The Personal Statement": {
                  lessons: [
                      { title: "Day 1: Unit Introduction: Writing for Your Future", standard: "11-12W2f" },
                      { title: "Day 2: Engage: Analyzing College Application Prompts", standard: "11-12R1" },
                      { title: "Day 3: What Makes a College Essay Effective?", standard: "11-12R9" },
                      { title: "Day 4: Brainstorming Workshop 1: Personal Inventory", standard: "11-12W3" },
                      { title: "Day 5: Brainstorming Workshop 2: Telling Small Stories", standard: "11-12W3" },
                      { title: "Day 6: Selecting a Topic", standard: "11-12W3" },
                      { title: "Day 7: Narrative Structure: The Anecdote-Reflection Model", standard: "11-12W3c" },
                      { title: "Day 8: Writing Workshop: The Opening Hook", standard: "11-12W3a" },
                      { title: "Day 9: Drafting the Anecdote", standard: "11-12W3b" },
                      { title: "Day 10: Drafting the Reflection", standard: "11-12W3e" },
                      { title: "Day 11: First Draft Due", standard: "11-12W3" },
                      { title: "Day 12: Self-Revision Workshop", standard: "11-12W3" },
                      { title: "Day 13: Peer Review Workshop 1", standard: "11-12W3" },
                      { title: "Day 14: Revision Workshop: Finding the 'So What?'", standard: "11-12W3e" },
                      { title: "Day 15: Peer Review Workshop 2", standard: "11-12W3" },
                      { title: "Day 16: Voice and Tone", standard: "11-12W2f" },
                      { title: "Day 17: Teacher-Student Conferences", standard: "11-12SL1" },
                      { title: "Day 18: Final Revisions", standard: "11-12W3" },
                      { title: "Day 19: Editing and Proofreading", standard: "11-12L1" },
                      { title: "Day 20: Polished Personal Statement Due", standard: "11-12W3" },
                      { title: "Day 21: Introduction to Career Writing: The Resume", standard: "11-12W2" },
                      { title: "Day 22: Resume Workshop: Brainstorming Content", standard: "11-12W2" },
                      { title: "Day 23: Resume Workshop: Action Verbs", standard: "11-12L6" },
                      { title: "Day 24: Drafting the Resume", standard: "11-12W2" },
                      { title: "Day 25: Resume Peer Review", standard: "11-12W2" },
                      { title: "Day 26: Revising and Finalizing the Resume", standard: "11-12W2" },
                      { title: "Day 27: Introduction to Professional Communication", standard: "11-12SL6" },
                      { title: "Day 28: Workshop: Writing a Professional Email", standard: "11-12W2" },
                      { title: "Day 29: Introduction to Interviewing", standard: "11-12SL6" },
                      { title: "Day 30: Workshop: Common Interview Questions", standard: "11-12SL4" },
                      { title: "Day 31: Mock Interview Preparation", standard: "11-12SL4" },
                      { title: "Day 32: Adapting Speech for a Formal Context", standard: "11-12SL6" },
                      { title: "Day 33: Mock Interviews Day 1", standard: "11-12SL1" },
                      { title: "Day 34: Mock Interviews Day 2", standard: "11-12SL1" },
                      { title: "Day 35: Interview Reflection and Thank-You Notes", standard: "11-12W2" },
                      { title: "Day 36: Scholarship Essay Workshop", standard: "11-12W1" },
                      { title: "Day 37: Writing a Scholarship Essay", standard: "11-12W1" },
                      { title: "Day 38: Researching Colleges and Careers", standard: "11-12W6" },
                      { title: "Day 39: Presenting Research Findings", standard: "11-12SL4" },
                      { title: "Day 40: Sharing Research", standard: "11-12SL4" },
                      { title: "Day 41: Creating a Professional Digital Presence", standard: "11-12SL5" },
                      { title: "Day 42: Portfolio Assembly", standard: "11-12W6" },
                      { title: "Day 43: Portfolio Presentation", standard: "11-12SL4" },
                      { title: "Day 44: Unit Closure Discussion", standard: "11-12SL1d" },
                      { title: "Day 45: Final Unit Reflection", standard: "11-12W4" }
                  ]
              }
          }
      }
    }
};
