export const ela10Curriculum = {
    units: {
        "Unit 1: Truth and Perspective": {
            topics: {
                "Point of View and Reliability": {
                    lessons: [
                        "Day 1: Unit Introduction: What is Truth?",
                        "Day 2: Engage: A Question of Truth",
                        "Day 3: Defining Point of View and Narrator Reliability",
                        "Day 4: Anchor Text Introduction",
                        "Day 5: Reading and First Impressions",
                        "Day 6: Analyzing Diction and Tone",
                        "Day 7: Tracking the Narrative",
                        "Day 8: Character Motivation",
                        "Day 9: Group Discussion: Is the Narrator Trustworthy?",
                        "Day 10: Writing Workshop: Character Voice Journal",
                        "Day 11: How Perspective Shapes Plot",
                        "Day 12: The Impact of an Unreliable Narrator",
                        "Day 13: Reading and Analyzing a Key Scene",
                        "Day 14: Socratic Seminar Preparation",
                        "Day 15: Socratic Seminar",
                        "Day 16: Connecting to Other Perspectives",
                        "Day 17: Comparative Analysis",
                        "Day 18: Introduction to the Analytical Essay",
                        "Day 19: Essay Workshop: Developing a Thesis",
                        "Day 20: Essay Workshop: Gathering Evidence",
                        "Day 21: Elaboration: Rewriting a Scene",
                        "Day 22: Creative Writing Workshop: Capturing a New Voice",
                        "Day 23: Peer Review: Creative Scene",
                        "Day 24: Sharing Rewritten Scenes",
                        "Day 25: Connecting Creative and Analytical Writing",
                        "Day 26: Essay Workshop: Outlining",
                        "Day 27: Drafting the Essay: Introduction and Body",
                        "Day 28: Drafting the Essay: Conclusion",
                        "Day 29: Figurative Language and Nuance",
                        "Day 30: Revising for Argument",
                        "Day 31: Revising for Clarity and Style",
                        "Day 32: Peer Review Workshop: Full Essay",
                        "Day 33: Final Revisions",
                        "Day 34: Editing and Proofreading",
                        "Day 35: Final Essay Submission",
                        "Day 36: Introduction to a New Text with Multiple Perspectives",
                        "Day 37: Comparing Narrative Structures",
                        "Day 38: Evaluating a Speaker's Perspective",
                        "Day 39: Discussion: Truth in Non-Fiction",
                        "Day 40: Debate: Is Objective Truth Possible?",
                        "Day 41: Creative Response Project Intro",
                        "Day 42: Creative Project Work Day",
                        "Day 43: Creative Project Work Day",
                        "Day 44: Project Showcase",
                        "Day 45: Unit Reflection"
                    ]
                }
            }
        },
        "Unit 2: Utopia and Dystopia": {
            topics: {
                "Analyzing Dystopian Societies": {
                    lessons: [
                        "Day 1: Unit Introduction: The Concept of Utopia",
                        "Day 2: Engage: Designing a Perfect World",
                        "Day 3: Presenting Utopias",
                        "Day 4: Characteristics of Dystopian Fiction",
                        "Day 5: Anchor Text Introduction",
                        "Day 6: World-Building Analysis",
                        "Day 7: Analyzing Dystopian Control",
                        "Day 8: The Dystopian Protagonist",
                        "Day 9: Reading and Discussion",
                        "Day 10: Writing Workshop: World-Building Paragraph",
                        "Day 11: Thematic Development: Conformity vs. Individuality",
                        "Day 12: Analyzing Propaganda",
                        "Day 13: Symbolism in Dystopian Literature",
                        "Day 14: Reading and Analyzing the Climax",
                        "Day 15: Socratic Seminar",
                        "Day 16: Connecting to the Real World: Research Mini-Project",
                        "Day 17: Research Day",
                        "Day 18: Making Connections",
                        "Day 19: Sharing Connections",
                        "Day 20: Summative Essay Introduction",
                        "Day 21: Essay Workshop: Thesis Development",
                        "Day 22: Essay Workshop: Gathering Evidence",
                        "Day 23: Essay Workshop: Outlining",
                        "Day 24: Drafting the Explanatory Essay",
                        "Day 25: Peer Review Workshop",
                        "Day 26: Revising the Essay",
                        "Day 27: Vocabulary and Precise Language",
                        "Day 28: Finalizing the Explanatory Essay",
                        "Day 29: Elaboration: Dystopia on Screen Intro",
                        "Day 30: Film Viewing Day 1",
                        "Day 31: Film Viewing Day 2",
                        "Day 32: Comparative Analysis: Book vs. Film",
                        "Day 33: Discussion: Analyzing Adaptation Choices",
                        "Day 34: Creative Response Intro: Your Dystopia",
                        "Day 35: Creative Project: World-Building",
                        "Day 36: Creative Project: The Protagonist",
                        "Day 37: Creative Project: Writing a Scene",
                        "Day 38: Creative Project Workshop",
                        "Day 39: Finalizing Creative Projects",
                        "Day 40: Submit Explanatory Essay",
                        "Day 41: Dystopian Showcase Day 1",
                        "Day 42: Dystopian Showcase Day 2",
                        "Day 43: Unit Closure Discussion",
                        "Day 44: Final Thematic Connection",
                        "Day 45: Unit Reflection"
                    ]
                }
            }
        },
        "Unit 3: Foundational Myths and Modern Meanings": {
            topics: {
                "Exploring Archetypes and Allusions": {
                    lessons: [
                        "Day 1: Unit Introduction: What is a Myth?",
                        "Day 2: Engage: Modern Heroes and Monsters",
                        "Day 3: The Hero's Journey",
                        "Day 4: Reading Foundational Myths 1: Creation Myths",
                        "Day 5: Reading Foundational Myths 2: Hero Myths",
                        "Day 6: Character Archetypes",
                        "Day 7: Anchor Text Introduction",
                        "Day 8: Identifying Mythological Parallels",
                        "Day 9: Analyzing Allusions",
                        "Day 10: Reading the Anchor Text",
                        "Day 11: Transformation of Character",
                        "Day 12: Transformation of Theme",
                        "Day 13: Discussion: Why Adapt Myths?",
                        "Day 14: Reading and Discussion",
                        "Day 15: Socratic Seminar",
                        "Day 16: Myths Across Media",
                        "Day 17: Comparative Analysis: Different Media",
                        "Day 18: Creative Response Project Introduction",
                        "Day 19: Brainstorming for Creative Adaptation",
                        "Day 20: Project Planning",
                        "Day 21: Creative Writing Workshop: Narrative",
                        "Day 22: Creative Writing Workshop: Poetry",
                        "Day 23: Creative Project Work Day",
                        "Day 24: Peer Review Workshop",
                        "Day 25: Revising Creative Projects",
                        "Day 26: Analytical Essay Introduction",
                        "Day 27: Essay Workshop: Comparative Thesis",
                        "Day 28: Essay Workshop: Structuring a Comparative Essay",
                        "Day 29: Essay Workshop: Gathering Evidence",
                        "Day 30: Drafting the Comparative Essay",
                        "Day 31: Finalizing Creative Projects",
                        "Day 32: Peer Review: Comparative Essay",
                        "Day 33: Revising the Comparative Essay",
                        "Day 34: Language Workshop: Academic Vocabulary",
                        "Day 35: Editing and Proofreading",
                        "Day 36: Submit Comparative Essay",
                        "Day 37: Presentation Skills Workshop",
                        "Day 38: Presentation Preparation",
                        "Day 39: Mythology Showcase Day 1",
                        "Day 40: Mythology Showcase Day 2",
                        "Day 41: Mythology Showcase Day 3",
                        "Day 42: Gallery Walk",
                        "Day 43: Unit Closure Discussion",
                        "Day 44: Connecting to Personal Experience",
                        "Day 45: Unit Reflection"
                    ]
                }
            }
        },
        "Unit 4: The Language of Poetry": {
            topics: {
                "Sound and Sense in Poetry": {
                    lessons: [
                        "Day 1: Unit Introduction: What is Poetry?",
                        "Day 2: Engage: Hearing the Music in Language",
                        "Day 3: Figurative Language 1: Simile and Metaphor",
                        "Day 4: Figurative Language 2: Personification and Imagery",
                        "Day 5: Sound Devices 1: Alliteration and Assonance",
                        "Day 6: Sound Devices 2: Rhyme and Rhythm",
                        "Day 7: Connotation and Denotation",
                        "Day 8: Close Reading a Poem: TP-CASTT",
                        "Day 9: Applying TP-CASTT",
                        "Day 10: Writing Workshop: Short Analysis",
                        "Day 11: Poetic Structure 1: The Stanza and the Line",
                        "Day 12: Poetic Structure 2: Fixed Forms (The Sonnet)",
                        "Day 13: Poetic Structure 3: Free Verse",
                        "Day 14: Comparing Forms",
                        "Day 15: Discussion: Form and Freedom",
                        "Day 16: Creative Writing Intro: Poetry Imitation",
                        "Day 17: Imitation Workshop 1: Sound",
                        "Day 18: Imitation Workshop 2: Figurative Language",
                        "Day 19: Imitation Workshop 3: Form",
                        "Day 20: Peer Review: Imitation Poems",
                        "Day 21: Creative Writing: Personal Experience",
                        "Day 22: Drafting Workshop 1: Getting Ideas Down",
                        "Day 23: Drafting Workshop 2: Shaping the Poem",
                        "Day 24: Revision Workshop: The Power of the Verb",
                        "Day 25: Revision Workshop: Cutting Clutter",
                        "Day 26: Poetry Peer Review",
                        "Day 27: Finalizing Personal Poems",
                        "Day 28: Poetry Anthology Project Introduction",
                        "Day 29: Selecting Poems for Anthology",
                        "Day 30: Writing Analyses for Anthology",
                        "Day 31: Anthology Work Day",
                        "Day 32: Anthology Peer Review",
                        "Day 33: Finalizing Anthologies",
                        "Day 34: Performance Poetry Intro",
                        "Day 35: Analyzing a Spoken Word Performance",
                        "Day 36: Preparing for a Poetry Slam",
                        "Day 37: Performance Workshop",
                        "Day 38: Presentation Visuals",
                        "Day 39: Poetry Slam Day 1",
                        "Day 40: Poetry Slam Day 2",
                        "Day 41: Poetry Slam Day 3",
                        "Day 42: Submit Poetry Anthology",
                        "Day 43: Found Poetry Workshop",
                        "Day 44: Unit Closure Discussion",
                        "Day 45: Unit Reflection"
                    ]
                }
            }
        }
    }
};
