export const ela11Curriculum = {
    units: {
        "Unit 1: The American Experience": {
            topics: {
                "Analyzing Foundational American Texts": {
                    lessons: [
                        "Day 1: Unit Introduction: The American Question",
                        "Day 2: Engage: Defining 'American'",
                        "Day 3: Reading Foundational Text 1",
                        "Day 4: Analyzing Rhetoric in Foundational Texts",
                        "Day 5: Reading Foundational Text 2: A Competing Vision",
                        "Day 6: Comparative Analysis Workshop",
                        "Day 7: Discussion: Ideals vs. Realities",
                        "Day 8: Anchor Text Introduction (e.g., The Great Gatsby)",
                        "Day 9: Reading and Annotating the Anchor Text",
                        "Day 10: Analyzing Character as Symbol",
                        "Day 11: The American Dream in the Anchor Text",
                        "Day 12: Socratic Seminar on the Anchor Text",
                        "Day 13: Literary Criticism 1: Introduction",
                        "Day 14: Applying a Critical Lens",
                        "Day 15: Writing Workshop: Integrating Critical Voices",
                        "Day 16: Connecting to Contemporary Voices: Poetry",
                        "Day 17: Connecting to Contemporary Voices: Non-Fiction",
                        "Day 18: Synthesis Discussion",
                        "Day 19: Introduction to the Synthesis Essay",
                        "Day 20: Essay Workshop: Formulating a Complex Thesis",
                        "Day 21: Essay Workshop: Selecting and Organizing Evidence",
                        "Day 22: Essay Workshop: Outlining the Synthesis Essay",
                        "Day 23: Drafting the Introduction",
                        "Day 24: Drafting Body Paragraphs with Synthesis",
                        "Day 25: Language Workshop: Varying Syntax",
                        "Day 26: Continued Drafting",
                        "Day 27: Self-Revision Workshop",
                        "Day 28: Peer Review Workshop",
                        "Day 29: Revision Planning",
                        "Day 30: Revising the Essay",
                        "Day 31: Workshop on Figurative Language and Nuance",
                        "Day 32: Editing and Proofreading",
                        "Day 33: Final Synthesis Essay Due",
                        "Day 34: Preparing for a Harkness Discussion",
                        "Day 35: Harkness Discussion Day 1",
                        "Day 36: Harkness Discussion Day 2",
                        "Day 37: Discussion Reflection",
                        "Day 38: Creative Response Project",
                        "Day 39: Creative Project Work Day",
                        "Day 40: Sharing Creative Responses",
                        "Day 41: Final Text: A Modern Speech",
                        "Day 42: Connecting Past and Present",
                        "Day 43: Unit Closure Discussion",
                        "Day 44: Portfolio Curation",
                        "Day 45: Unit Reflection"
                    ]
                }
            }
        },
        "Unit 2: The Author's Craft": {
            topics: {
                "Deconstructing Authorial Style": {
                    lessons: [
                        "Day 1: Unit Introduction: What is Style?",
                        "Day 2: Engage: Recognizing a Voice",
                        "Day 3: Author Study Introduction",
                        "Day 4: Reading and Annotating for Style",
                        "Day 5: Deconstructing Diction",
                        "Day 6: Deconstructing Syntax",
                        "Day 7: Discussion: The 'Stylistic Fingerprint'",
                        "Day 8: Reading Anchor Text 2",
                        "Day 9: Analyzing Tone and Mood",
                        "Day 10: Workshop: Writing a Style Analysis Paragraph",
                        "Day 11: Analyzing Narrative Structure",
                        "Day 12: Analyzing Thematic Development",
                        "Day 13: Figurative Language and Symbolism",
                        "Day 14: Socratic Seminar Preparation",
                        "Day 15: Socratic Seminar: Style and Meaning",
                        "Day 16: Literary Criticism on the Author",
                        "Day 17: Synthesizing Critical Perspectives",
                        "Day 18: Introduction to the Literary Argument Essay",
                        "Day 19: Essay Workshop: Formulating a Nuanced Thesis",
                        "Day 20: Essay Workshop: Organizing the Argument",
                        "Day 21: Elaboration: Mentor Text Imitation",
                        "Day 22: Creative Writing: Imitating the Master",
                        "Day 23: Peer Review: Style Imitations",
                        "Day 24: Reflection on Imitation",
                        "Day 25: Drafting the Literary Argument: Introduction",
                        "Day 26: Drafting Body Paragraphs: Diction and Syntax",
                        "Day 27: Drafting Body Paragraphs: Structure and Theme",
                        "Day 28: Drafting with a Critical Voice",
                        "Day 29: Drafting the Conclusion",
                        "Day 30: Self-Revision Workshop",
                        "Day 31: Peer Review Workshop: Full Draft",
                        "Day 32: Revising for a Formal Tone",
                        "Day 33: Final Revisions",
                        "Day 34: Editing Workshop: Advanced Conventions",
                        "Day 35: Final Literary Argument Due",
                        "Day 36: Panel Presentation Introduction",
                        "Day 37: Group Work: Planning the Panel",
                        "Day 38: Creating Presentation Materials",
                        "Day 39: Presentation Rehearsals",
                        "Day 40: Panel Presentations Day 1",
                        "Day 41: Panel Presentations Day 2",
                        "Day 42: Responding to Other Texts by the Author",
                        "Day 43: Unit Closure Discussion",
                        "Day 44: Vocabulary Acquisition",
                        "Day 45: Unit Reflection"
                    ]
                }
            }
        },
        "Unit 3: Shakespeare and Adaptation": {
            topics: {
                "Reading Shakespeare": {
                    lessons: [
                        "Day 1: Unit Introduction: Shakespeare's Legacy",
                        "Day 2: Engage: Shakespeare in Pop Culture",
                        "Day 3: Introduction to the Anchor Play",
                        "Day 4: Reading Act I",
                        "Day 5: Analyzing the Inciting Incident",
                        "Day 6: Understanding Shakespearean Language",
                        "Day 7: Reading Act II",
                        "Day 8: Workshop: The Soliloquy",
                        "Day 9: Performance Analysis",
                        "Day 10: Character Foils",
                        "Day 11: Reading Act III",
                        "Day 12: Analyzing the Climax",
                        "Day 13: Thematic Development",
                        "Day 14: Socratic Seminar",
                        "Day 15: Reading Act IV",
                        "Day 16: Reading Act V",
                        "Day 17: Discussion: Tragic Hero",
                        "Day 18: Introduction to Adaptation",
                        "Day 19: Analyzing a Film Adaptation 1",
                        "Day 20: Analyzing a Film Adaptation 2",
                        "Day 21: Comparative Discussion: Play vs. Film",
                        "Day 22: Focus on a Scene: Textual Analysis",
                        "Day 23: Focus on a Scene: Comparative Film Analysis",
                        "Day 24: Workshop: Writing a Comparative Analysis",
                        "Day 25: Evaluating Adaptations",
                        "Day 26: Creative Response: Modern Adaptation Intro",
                        "Day 27: Brainstorming a Modern Context",
                        "Day 28: Scriptwriting Workshop",
                        "Day 29: Drafting the Modern Scene",
                        "Day 30: Peer Review: Modern Scenes",
                        "Day 31: Revising the Modern Scene",
                        "Day 32: Summative Project: Performance/Analysis Intro",
                        "Day 33: Project Work Day 1",
                        "Day 34: Performance Track: Rehearsal",
                        "Day 35: Analysis Track: Thesis Development",
                        "Day 36: Performance Track: Tech and Props",
                        "Day 37: Analysis Track: Outlining and Drafting",
                        "Day 38: Project Work Day: Teacher Conferencing",
                        "Day 39: Final Project Work Day",
                        "Day 40: Shakespeare Festival Day 1: Performances",
                        "Day 41: Shakespeare Festival Day 2: Performances",
                        "Day 42: Analytical Essay Submission",
                        "Day 43: Performance Reflection",
                        "Day 44: Unit Closure Discussion",
                        "Day 45: Unit Reflection"
                    ]
                }
            }
        },
        "Unit 4: The Researched Argument": {
            topics: {
                "Building a Complex Argument": {
                    lessons: [
                        "Day 1: Unit Introduction: Writing as Action",
                        "Day 2: Engage: Identifying Public Conversations",
                        "Day 3: Topic Selection and Initial Exploration",
                        "Day 4: Formulating a Research Question",
                        "Day 5: Advanced Source Evaluation",
                        "Day 6: Research Workshop: Academic Databases",
                        "Day 7: Reading and Annotating Scholarly Articles",
                        "Day 8: Synthesizing Sources: Finding the Conversation",
                        "Day 9: Note-Taking and Annotated Bibliography",
                        "Day 10: Developing a Nuanced Thesis",
                        "Day 11: Acknowledging and Responding to Counterclaims",
                        "Day 12: Structuring a Complex Argument",
                        "Day 13: Drafting the Introduction",
                        "Day 14: Drafting Body Paragraphs: Integrating Evidence",
                        "Day 15: Workshop on Logical Fallacies",
                        "Day 16: Continued Drafting",
                        "Day 17: Drafting the Conclusion",
                        "Day 18: Self-Revision Workshop",
                        "Day 19: Peer Review Workshop",
                        "Day 20: Revising the Argument",
                        "Day 21: Language and Style Workshop",
                        "Day 22: Transitions and Cohesion",
                        "Day 23: Citation and Formatting Workshop (MLA/APA)",
                        "Day 24: Final Editing and Proofreading",
                        "Day 25: Research Paper Submission",
                        "Day 26: From Research to Advocacy: Presentation Intro",
                        "Day 27: Identifying Audience and Purpose",
                        "Day 28: Structuring the Advocacy Presentation",
                        "Day 29: Using Rhetoric for a Live Audience",
                        "Day 30: Creating Visuals for Advocacy",
                        "Day 31: Workshop: Delivery and Presence",
                        "Day 32: Presentation Rehearsal and Feedback",
                        "Day 33: Advocacy Presentations Day 1",
                        "Day 34: Advocacy Presentations Day 2",
                        "Day 35: Evaluating a Speaker's Argument",
                        "Day 36: Q&A and Discussion",
                        "Day 37: Advocacy Presentations Day 3",
                        "Day 38: Advocacy Presentations Day 4",
                        "Day 39: Connecting to Other Media",
                        "Day 40: Synthesizing Across Formats",
                        "Day 41: Writing a 'Letter to the Editor'",
                        "Day 42: Workshop: Writing for a Public Audience",
                        "Day 43: Unit Closure: Symposium of Ideas",
                        "Day 44: Acquiring Academic Vocabulary",
                        "Day 45: Final Unit Reflection"
                    ]
                }
            }
        }
    }
};
