
export const ela11Curriculum = {
    units: {
        "Unit 1: The American Experience": {
            topics: {
                "Analyzing Foundational American Texts": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: The American Question", standard: "11-12SL1" },
                        { title: "Day 2: Engage: Defining 'American'", standard: "11-12W4" },
                        { title: "Day 3: Reading Foundational Text 1", standard: "11-12R2" },
                        { title: "Day 4: Analyzing Rhetoric in Foundational Texts", standard: "11-12R6" },
                        { title: "Day 5: Reading Foundational Text 2: A Competing Vision", standard: "11-12R9" },
                        { title: "Day 6: Comparative Analysis Workshop", standard: "11-12W2" },
                        { title: "Day 7: Discussion: Ideals vs. Realities", standard: "11-12SL1" },
                        { title: "Day 8: Anchor Text Introduction (e.g., The Great Gatsby)", standard: "11-12R2" },
                        { title: "Day 9: Reading and Annotating the Anchor Text", standard: "11-12R1" },
                        { title: "Day 10: Analyzing Character as Symbol", standard: "11-12R3" },
                        { title: "Day 11: The American Dream in the Anchor Text", standard: "11-12R2" },
                        { title: "Day 12: Socratic Seminar on the Anchor Text", standard: "11-12SL1d" },
                        { title: "Day 13: Literary Criticism 1: Introduction", standard: "11-12R8" },
                        { title: "Day 14: Applying a Critical Lens", standard: "11-12R8" },
                        { title: "Day 15: Writing Workshop: Integrating Critical Voices", standard: "11-12W5" },
                        { title: "Day 16: Connecting to Contemporary Voices: Poetry", standard: "11-12R9" },
                        { title: "Day 17: Connecting to Contemporary Voices: Non-Fiction", standard: "11-12R9" },
                        { title: "Day 18: Synthesis Discussion", standard: "11-12SL1d" },
                        { title: "Day 19: Introduction to the Synthesis Essay", standard: "11-12W1" },
                        { title: "Day 20: Essay Workshop: Formulating a Complex Thesis", standard: "11-12W1a" },
                        { title: "Day 21: Essay Workshop: Selecting and Organizing Evidence", standard: "11-12W1b" },
                        { title: "Day 22: Essay Workshop: Outlining the Synthesis Essay", standard: "11-12W1a" },
                        { title: "Day 23: Drafting the Introduction", standard: "11-12W1a" },
                        { title: "Day 24: Drafting Body Paragraphs with Synthesis", standard: "11-12W1b" },
                        { title: "Day 25: Language Workshop: Varying Syntax", standard: "11-12L3a" },
                        { title: "Day 26: Continued Drafting", standard: "11-12W1" },
                        { title: "Day 27: Self-Revision Workshop", standard: "11-12W1" },
                        { title: "Day 28: Peer Review Workshop", standard: "11-12W1" },
                        { title: "Day 29: Revision Planning", standard: "11-12W1" },
                        { title: "Day 30: Revising the Essay", standard: "11-12W1" },
                        { title: "Day 31: Workshop on Figurative Language and Nuance", standard: "11-12L5" },
                        { title: "Day 32: Editing and Proofreading", standard: "11-12L1" },
                        { title: "Day 33: Final Synthesis Essay Due", standard: "11-12W1" },
                        { title: "Day 34: Preparing for a Harkness Discussion", standard: "11-12SL1a" },
                        { title: "Day 35: Harkness Discussion Day 1", standard: "11-12SL1" },
                        { title: "Day 36: Harkness Discussion Day 2", standard: "11-12SL1" },
                        { title: "Day 37: Discussion Reflection", standard: "11-12W4" },
                        { title: "Day 38: Creative Response Project", standard: "11-12W4" },
                        { title: "Day 39: Creative Project Work Day", standard: "11-12W4" },
                        { title: "Day 40: Sharing Creative Responses", standard: "11-12SL4" },
                        { title: "Day 41: Final Text: A Modern Speech", standard: "11-12R8" },
                        { title: "Day 42: Connecting Past and Present", standard: "11-12R9" },
                        { title: "Day 43: Unit Closure Discussion", standard: "11-12SL1d" },
                        { title: "Day 44: Portfolio Curation", standard: "11-12W6" },
                        { title: "Day 45: Unit Reflection", standard: "11-12W4" }
                    ]
                }
            }
        },
        "Unit 2: The Author's Craft": {
            topics: {
                "Deconstructing Authorial Style": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: What is Style?", standard: "11-12R4" },
                        { title: "Day 2: Engage: Recognizing a Voice", standard: "11-12SL3" },
                        { title: "Day 3: Author Study Introduction", standard: "11-12W6" },
                        { title: "Day 4: Reading and Annotating for Style", standard: "11-12R1" },
                        { title: "Day 5: Deconstructing Diction", standard: "11-12R4" },
                        { title: "Day 6: Deconstructing Syntax", standard: "11-12L3a" },
                        { title: "Day 7: Discussion: The 'Stylistic Fingerprint'", standard: "11-12SL1" },
                        { title: "Day 8: Reading Anchor Text 2", standard: "11-12R1" },
                        { title: "Day 9: Analyzing Tone and Mood", standard: "11-12R4" },
                        { title: "Day 10: Workshop: Writing a Style Analysis Paragraph", standard: "11-12W2" },
                        { title: "Day 11: Analyzing Narrative Structure", standard: "11-12R5" },
                        { title: "Day 12: Analyzing Thematic Development", standard: "11-12R2" },
                        { title: "Day 13: Figurative Language and Symbolism", standard: "11-12L5a" },
                        { title: "Day 14: Socratic Seminar Preparation", standard: "11-12SL1a" },
                        { title: "Day 15: Socratic Seminar: Style and Meaning", standard: "11-12SL1" },
                        { title: "Day 16: Literary Criticism on the Author", standard: "11-12R8" },
                        { title: "Day 17: Synthesizing Critical Perspectives", standard: "11-12SL2" },
                        { title: "Day 18: Introduction to the Literary Argument Essay", standard: "11-12W1" },
                        { title: "Day 19: Essay Workshop: Formulating a Nuanced Thesis", standard: "11-12W1a" },
                        { title: "Day 20: Essay Workshop: Organizing the Argument", standard: "11-12W1a" },
                        { title: "Day 21: Elaboration: Mentor Text Imitation", standard: "11-12W4" },
                        { title: "Day 22: Creative Writing: Imitating the Master", standard: "11-12W3" },
                        { title: "Day 23: Peer Review: Style Imitations", standard: "11-12W3" },
                        { title: "Day 24: Reflection on Imitation", standard: "11-12W4" },
                        { title: "Day 25: Drafting the Literary Argument: Introduction", standard: "11-12W1a" },
                        { title: "Day 26: Drafting Body Paragraphs: Diction and Syntax", standard: "11-12W1b" },
                        { title: "Day 27: Drafting Body Paragraphs: Structure and Theme", standard: "11-12W1b" },
                        { title: "Day 28: Drafting with a Critical Voice", standard: "11-12W1b" },
                        { title: "Day 29: Drafting the Conclusion", standard: "11-12W1e" },
                        { title: "Day 30: Self-Revision Workshop", standard: "11-12W1" },
                        { title: "Day 31: Peer Review Workshop: Full Draft", standard: "11-12W1" },
                        { title: "Day 32: Revising for a Formal Tone", standard: "11-12W1f" },
                        { title: "Day 33: Final Revisions", standard: "11-12L1" },
                        { title: "Day 34: Editing Workshop: Advanced Conventions", standard: "11-12L2" },
                        { title: "Day 35: Final Literary Argument Due", standard: "11-12W1" },
                        { title: "Day 36: Panel Presentation Introduction", standard: "11-12SL4" },
                        { title: "Day 37: Group Work: Planning the Panel", standard: "11-12SL1b" },
                        { title: "Day 38: Creating Presentation Materials", standard: "11-12SL5" },
                        { title: "Day 39: Presentation Rehearsals", standard: "11-12SL1" },
                        { title: "Day 40: Panel Presentations Day 1", standard: "11-12SL4" },
                        { title: "Day 41: Panel Presentations Day 2", standard: "11-12SL4" },
                        { title: "Day 42: Responding to Other Texts by the Author", standard: "11-12R9" },
                        { title: "Day 43: Unit Closure Discussion", standard: "11-12SL1d" },
                        { title: "Day 44: Vocabulary Acquisition", standard: "11-12L6" },
                        { title: "Day 45: Unit Reflection", standard: "11-12W4" }
                    ]
                }
            }
        },
        "Unit 3: Shakespeare and Adaptation": {
            topics: {
                "Reading Shakespeare": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: Shakespeare's Legacy", standard: "11-12R9" },
                        { title: "Day 2: Engage: Shakespeare in Pop Culture", standard: "11-12R7" },
                        { title: "Day 3: Introduction to the Anchor Play", standard: "11-12R2" },
                        { title: "Day 4: Reading Act I", standard: "11-12R1" },
                        { title: "Day 5: Analyzing the Inciting Incident", standard: "11-12R3" },
                        { title: "Day 6: Understanding Shakespearean Language", standard: "11-12L4" },
                        { title: "Day 7: Reading Act II", standard: "11-12R1" },
                        { title: "Day 8: Workshop: The Soliloquy", standard: "11-12R5" },
                        { title: "Day 9: Performance Analysis", standard: "11-12R7" },
                        { title: "Day 10: Character Foils", standard: "11-12R3" },
                        { title: "Day 11: Reading Act III", standard: "11-12R1" },
                        { title: "Day 12: Analyzing the Climax", standard: "11-12R3" },
                        { title: "Day 13: Thematic Development", standard: "11-12R2" },
                        { title: "Day 14: Socratic Seminar", standard: "11-12SL1" },
                        { title: "Day 15: Reading Act IV", standard: "11-12R1" },
                        { title: "Day 16: Reading Act V", standard: "11-12R1" },
                        { title: "Day 17: Discussion: Tragic Hero", standard: "11-12R3" },
                        { title: "Day 18: Introduction to Adaptation", standard: "11-12R7" },
                        { title: "Day 19: Analyzing a Film Adaptation 1", standard: "11-12R7" },
                        { title: "Day 20: Analyzing a Film Adaptation 2", standard: "11-12R7" },
                        { title: "Day 21: Comparative Discussion: Play vs. Film", standard: "11-12SL1" },
                        { title: "Day 22: Focus on a Scene: Textual Analysis", standard: "11-12R1" },
                        { title: "Day 23: Focus on a Scene: Comparative Film Analysis", standard: "11-12R7" },
                        { title: "Day 24: Workshop: Writing a Comparative Analysis", standard: "11-12W2" },
                        { title: "Day 25: Evaluating Adaptations", standard: "11-12R7" },
                        { title: "Day 26: Creative Response: Modern Adaptation Intro", standard: "11-12W4" },
                        { title: "Day 27: Brainstorming a Modern Context", standard: "11-12W3" },
                        { title: "Day 28: Scriptwriting Workshop", standard: "11-12W3" },
                        { title: "Day 29: Drafting the Modern Scene", standard: "11-12W3" },
                        { title: "Day 30: Peer Review: Modern Scenes", standard: "11-12W3" },
                        { title: "Day 31: Revising the Modern Scene", standard: "11-12W3" },
                        { title: "Day 32: Summative Project: Performance/Analysis Intro", standard: "11-12W4" },
                        { title: "Day 33: Project Work Day 1", standard: "11-12W4" },
                        { title: "Day 34: Performance Track: Rehearsal", standard: "11-12SL6" },
                        { title: "Day 35: Analysis Track: Thesis Development", standard: "11-12W1a" },
                        { title: "Day 36: Performance Track: Tech and Props", standard: "11-12SL5" },
                        { title: "Day 37: Analysis Track: Outlining and Drafting", standard: "11-12W1" },
                        { title: "Day 38: Project Work Day: Teacher Conferencing", standard: "11-12SL1" },
                        { title: "Day 39: Final Project Work Day", standard: "11-12W1" },
                        { title: "Day 40: Shakespeare Festival Day 1: Performances", standard: "11-12SL4" },
                        { title: "Day 41: Shakespeare Festival Day 2: Performances", standard: "11-12SL4" },
                        { title: "Day 42: Analytical Essay Submission", standard: "11-12W1" },
                        { title: "Day 43: Performance Reflection", standard: "11-12W4" },
                        { title: "Day 44: Unit Closure Discussion", standard: "11-12SL1d" },
                        { title: "Day 45: Unit Reflection", standard: "11-12W4" }
                    ]
                }
            }
        },
        "Unit 4: The Researched Argument": {
            topics: {
                "Building a Complex Argument": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: Writing as Action", standard: "11-12W1" },
                        { title: "Day 2: Engage: Identifying Public Conversations", standard: "11-12SL2" },
                        { title: "Day 3: Topic Selection and Initial Exploration", standard: "11-12W6" },
                        { title: "Day 4: Formulating a Research Question", standard: "11-12W6" },
                        { title: "Day 5: Advanced Source Evaluation", standard: "11-12W7" },
                        { title: "Day 6: Research Workshop: Academic Databases", standard: "11-12W7" },
                        { title: "Day 7: Reading and Annotating Scholarly Articles", standard: "11-12R1" },
                        { title: "Day 8: Synthesizing Sources: Finding the Conversation", standard: "11-12W7" },
                        { title: "Day 9: Note-Taking and Annotated Bibliography", standard: "11-12W7" },
                        { title: "Day 10: Developing a Nuanced Thesis", standard: "11-12W1a" },
                        { title: "Day 11: Acknowledging and Responding to Counterclaims", standard: "11-12W1a" },
                        { title: "Day 12: Structuring a Complex Argument", standard: "11-12W1a" },
                        { title: "Day 13: Drafting the Introduction", standard: "11-12W1a" },
                        { title: "Day 14: Drafting Body Paragraphs: Integrating Evidence", standard: "11-12W1b" },
                        { title: "Day 15: Workshop on Logical Fallacies", standard: "11-12R8" },
                        { title: "Day 16: Continued Drafting", standard: "11-12W1" },
                        { title: "Day 17: Drafting the Conclusion", standard: "11-12W1e" },
                        { title: "Day 18: Self-Revision Workshop", standard: "11-12W1" },
                        { title: "Day 19: Peer Review Workshop", standard: "11-12W1" },
                        { title: "Day 20: Revising the Argument", standard: "11-12W1" },
                        { title: "Day 21: Language and Style Workshop", standard: "11-12L3" },
                        { title: "Day 22: Transitions and Cohesion", standard: "11-12W1d" },
                        { title: "Day 23: Citation and Formatting Workshop (MLA/APA)", standard: "11-12W7" },
                        { title: "Day 24: Final Editing and Proofreading", standard: "11-12L2" },
                        { title: "Day 25: Research Paper Submission", standard: "11-12W1" },
                        { title: "Day 26: From Research to Advocacy: Presentation Intro", standard: "11-12SL4" },
                        { title: "Day 27: Identifying Audience and Purpose", standard: "11-12SL4" },
                        { title: "Day 28: Structuring the Advocacy Presentation", standard: "11-12SL4" },
                        { title: "Day 29: Using Rhetoric for a Live Audience", standard: "11-12SL3" },
                        { title: "Day 30: Creating Visuals for Advocacy", standard: "11-12SL5" },
                        { title: "Day 31: Workshop: Delivery and Presence", standard: "11-12SL6" },
                        { title: "Day 32: Presentation Rehearsal and Feedback", standard: "11-12SL1" },
                        { title: "Day 33: Advocacy Presentations Day 1", standard: "11-12SL4" },
                        { title: "Day 34: Advocacy Presentations Day 2", standard: "11-12SL4" },
                        { title: "Day 35: Evaluating a Speaker's Argument", standard: "11-12SL3" },
                        { title: "Day 36: Q&A and Discussion", standard: "11-12SL1" },
                        { title: "Day 37: Advocacy Presentations Day 3", standard: "11-12SL4" },
                        { title: "Day 38: Advocacy Presentations Day 4", standard: "11-12SL4" },
                        { title: "Day 39: Connecting to Other Media", standard: "11-12R7" },
                        { title: "Day 40: Synthesizing Across Formats", standard: "11-12R7" },
                        { title: "Day 41: Writing a 'Letter to the Editor'", standard: "11-12W1" },
                        { title: "Day 42: Workshop: Writing for a Public Audience", standard: "11-12W1" },
                        { title: "Day 43: Unit Closure: Symposium of Ideas", standard: "11-12SL1d" },
                        { title: "Day 44: Acquiring Academic Vocabulary", standard: "11-12L6" },
                        { title: "Day 45: Final Unit Reflection", standard: "11-12W4" }
                    ]
                }
            }
        }
    }
};
