export const ela12Curriculum = {
    units: {
      "Unit 1: Choice and Consequence": {
          topics: {
              "Analyzing Complex Characters": {
                  lessons: [
                      "Day 1: Unit Introduction: Fate and Free Will",
                      "Day 2: Engage: A Moral Dilemma",
                      "Day 3: Anchor Text Introduction",
                      "Day 4: Reading and Identifying Core Conflicts",
                      "Day 5: Analyzing Character Motivation",
                      "Day 6: Moral Ambiguity",
                      "Day 7: Reading and Discussion",
                      "Day 8: Choice-and-Consequence Mapping",
                      "Day 9: Thematic Development: Guilt and Responsibility",
                      "Day 10: Socratic Seminar",
                      "Day 11: Analyzing Structure and Pacing",
                      "Day 12: Literary Theory 1: Psychoanalytic Lens",
                      "Day 13: Literary Theory 2: Existentialist Lens",
                      "Day 14: Applying Critical Lenses",
                      "Day 15: Reading and Discussion to Conclusion",
                      "Day 16: Debate: A Character on Trial",
                      "Day 17: Introduction to the Literary Argument Essay",
                      "Day 18: Essay Workshop: Complex Thesis",
                      "Day 19: Essay Workshop: Using Ambiguous Evidence",
                      "Day 20: Essay Workshop: Outlining",
                      "Day 21: Drafting Workshop: Introduction",
                      "Day 22: Drafting Workshop: Body Paragraphs",
                      "Day 23: Language Workshop: Syntax for Effect",
                      "Day 24: Drafting Workshop: Conclusion",
                      "Day 25: Self-Revision Workshop",
                      "Day 26: Peer Review Workshop",
                      "Day 27: Teacher-Student Conferences",
                      "Day 28: Revision Planning",
                      "Day 29: Revising the Essay",
                      "Day 30: Editing and Proofreading",
                      "Day 31: Final Essay Submission",
                      "Day 32: Elaboration: Philosophical Chairs",
                      "Day 33: Debate Reflection",
                      "Day 34: Connecting to Film",
                      "Day 35: Connecting to Personal Experience",
                      "Day 36: Introduction to the Final Project",
                      "Day 37: Project Proposal Workshop",
                      "Day 38: Project Work Day",
                      "Day 39: Project Work Day",
                      "Day 40: Project Work Day",
                      "Day 41: Final Project Presentations Day 1",
                      "Day 42: Final Project Presentations Day 2",
                      "Day 43: Unit Closure Discussion",
                      "Day 44: Portfolio Selection",
                      "Day 45: Unit Reflection"
                  ]
              }
          }
      },
      "Unit 2: Reading the World": {
          topics: {
              "Exploring Global Literature": {
                  lessons: [
                      "Day 1: Unit Introduction: Mapping Our Literary Worlds",
                      "Day 2: Engage: Universal Themes",
                      "Day 3: Anchor Text Introduction",
                      "Day 4: Context Workshop: Researching the Culture",
                      "Day 5: Reading and Annotating for Cultural Perspective",
                      "Day 6: Discussing Initial Readings",
                      "Day 7: Reading the Anchor Text",
                      "Day 8: Analyzing Character through a Cultural Lens",
                      "Day 9: Thematic Development",
                      "Day 10: Writing Workshop: Cultural Analysis",
                      "Day 11: Continued Reading and Discussion",
                      "Day 12: Author's Purpose and Message",
                      "Day 13: Making Connections to Personal Experience",
                      "Day 14: Socratic Seminar Preparation",
                      "Day 15: Socratic Seminar",
                      "Day 16: Introduction to the Explanatory Essay",
                      "Day 17: Essay Workshop: Thesis Development",
                      "Day 18: Essay Workshop: Gathering Evidence",
                      "Day 19: Essay Workshop: Outlining",
                      "Day 20: Drafting the Essay",
                      "Day 21: Peer Review Workshop",
                      "Day 22: Revising the Essay",
                      "Day 23: Language Workshop: Vocabulary",
                      "Day 24: Finalizing the Explanatory Essay",
                      "Day 25: Explanatory Essay Due",
                      "Day 26: Elaboration: Exploring World Literature through Poetry",
                      "Day 27: Discussion: Universal vs. Culturally Specific",
                      "Day 28: Creative Response Project Introduction",
                      "Day 29: Project Brainstorming and Planning",
                      "Day 30: Project Work Day 1",
                      "Day 31: Project Work Day 2",
                      "Day 32: Project Work Day 3",
                      "Day 33: Connecting to Other Media: World Cinema",
                      "Day 34: Comparative Discussion: Literature and Film",
                      "Day 35: Guest Speaker or Virtual Tour",
                      "Day 36: Student-Led Presentations: Cultural Spotlight",
                      "Day 37: Presentations Day 1",
                      "Day 38: Presentations Day 2",
                      "Day 39: Synthesizing Across Presentations",
                      "Day 40: Showcase of Creative Projects",
                      "Day 41: Artist's Statement Workshop",
                      "Day 42: Unit Closure Discussion",
                      "Day 43: Acquiring Academic Vocabulary",
                      "Day 44: Portfolio Curation",
                      "Day 45: Final Unit Reflection"
                  ]
              }
          }
      },
      "Unit 3: Satire and Social Critique": {
          topics: {
              "Understanding Satire": {
                  lessons: [
                      "Day 1: Unit Introduction: The Power of Humor",
                      "Day 2: Engage: Analyzing Contemporary Satire",
                      "Day 3: The Satirist's Toolkit",
                      "Day 4: Anchor Text Introduction",
                      "Day 5: Reading and Deconstructing the Anchor Text",
                      "Day 6: Analyzing Ironic Tone",
                      "Day 7: Hyperbole and Understatement",
                      "Day 8: Delineating the Satirical Argument",
                      "Day 9: Discussion: The Satirical Target",
                      "Day 10: Writing Workshop: Satirical Analysis",
                      "Day 11: Continued Reading and Analysis",
                      "Day 12: The Role of Logic in Satire",
                      "Day 13: Evaluating the Argument",
                      "Day 14: Socratic Seminar",
                      "Day 15: Introduction to the Explanatory Essay",
                      "Day 16: Essay Workshop: Thesis Development",
                      "Day 17: Essay Workshop: Gathering Evidence",
                      "Day 18: Essay Workshop: Outlining",
                      "Day 19: Drafting the Essay",
                      "Day 20: Peer Review and Revision",
                      "Day 21: Elaboration: Satire in Different Media",
                      "Day 22: Analyzing Political Cartoons",
                      "Day 23: Evaluating a Speaker's Satirical Argument",
                      "Day 24: Discussion: The Motives of Satire",
                      "Day 25: Introduction to the Creative Satire Project",
                      "Day 26: Brainstorming Topics for Satire",
                      "Day 27: Choosing a Satirical Mode",
                      "Day 28: Creative Project Work Day: Drafting",
                      "Day 29: Workshop: Creating an Ironic Persona",
                      "Day 30: Creative Project Peer Review",
                      "Day 31: Revising Creative Projects",
                      "Day 32: Finalizing Creative Projects",
                      "Day 33: Finalizing the Analytical Essay",
                      "Day 34: Essay Submission",
                      "Day 35: Preparing for the Satire Showcase",
                      "Day 36: Presentation Workshop: Using Visuals",
                      "Day 37: Satire Showcase Day 1",
                      "Day 38: Satire Showcase Day 2",
                      "Day 39: Satire Showcase Day 3",
                      "Day 40: Audience Response and Discussion",
                      "Day 41: The Limits and Dangers of Satire",
                      "Day 42: Debate: The Responsibility of the Satirist",
                      "Day 43: Final Text Analysis",
                      "Day 44: Portfolio Selection and Reflection",
                      "Day 45: Unit Reflection"
                  ]
              }
          }
      },
      "Unit 4: Crafting the Future: College and Career Writing": {
          topics: {
              "The Personal Statement": {
                  lessons: [
                      "Day 1: Unit Introduction: Writing for Your Future",
                      "Day 2: Engage: Analyzing College Application Prompts",
                      "Day 3: What Makes a College Essay Effective?",
                      "Day 4: Brainstorming Workshop 1: Personal Inventory",
                      "Day 5: Brainstorming Workshop 2: Telling Small Stories",
                      "Day 6: Selecting a Topic",
                      "Day 7: Narrative Structure: The Anecdote-Reflection Model",
                      "Day 8: Writing Workshop: The Opening Hook",
                      "Day 9: Drafting the Anecdote",
                      "Day 10: Drafting the Reflection",
                      "Day 11: First Draft Due",
                      "Day 12: Self-Revision Workshop",
                      "Day 13: Peer Review Workshop 1",
                      "Day 14: Revision Workshop: Finding the 'So What?'",
                      "Day 15: Peer Review Workshop 2",
                      "Day 16: Voice and Tone",
                      "Day 17: Teacher-Student Conferences",
                      "Day 18: Final Revisions",
                      "Day 19: Editing and Proofreading",
                      "Day 20: Polished Personal Statement Due",
                      "Day 21: Introduction to Career Writing: The Resume",
                      "Day 22: Resume Workshop: Brainstorming Content",
                      "Day 23: Resume Workshop: Action Verbs",
                      "Day 24: Drafting the Resume",
                      "Day 25: Resume Peer Review",
                      "Day 26: Revising and Finalizing the Resume",
                      "Day 27: Introduction to Professional Communication",
                      "Day 28: Workshop: Writing a Professional Email",
                      "Day 29: Introduction to Interviewing",
                      "Day 30: Workshop: Common Interview Questions",
                      "Day 31: Mock Interview Preparation",
                      "Day 32: Adapting Speech for a Formal Context",
                      "Day 33: Mock Interviews Day 1",
                      "Day 34: Mock Interviews Day 2",
                      "Day 35: Interview Reflection and Thank-You Notes",
                      "Day 36: Scholarship Essay Workshop",
                      "Day 37: Writing a Scholarship Essay",
                      "Day 38: Researching Colleges and Careers",
                      "Day 39: Presenting Research Findings",
                      "Day 40: Sharing Research",
                      "Day 41: Creating a Professional Digital Presence",
                      "Day 42: Portfolio Assembly",
                      "Day 43: Portfolio Presentation",
                      "Day 44: Unit Closure Discussion",
                      "Day 45: Final Unit Reflection"
                  ]
              }
          }
      }
    }
};
