export const ela9Curriculum = {
    units: {
      "Unit 1: Journeys of Identity": {
          topics: {
              "Analyzing Narrative and Character in 'The House on Mango Street'": {
                  lessons: [
                      "Day 1: Unit Introduction: What is Identity?",
                      "Day 2: Engage: Identity Mapping",
                      "Day 3: Anchor Text Introduction: First Look",
                      "Day 4: Close Reading & Annotation Practice",
                      "Day 5: Discussion: First Impressions",
                      "Day 6: Citing Textual Evidence",
                      "Day 7: Figurative Language Workshop 1",
                      "Day 8: Analyzing Character Voice",
                      "Day 9: Reading for Thematic Development",
                      "Day 10: Writing Workshop: Claim-Evidence-Reasoning",
                      "Day 11: Thematic Analysis: Shame and Hope",
                      "Day 12: Group Discussion: Thematic Patterns",
                      "Day 13: Figurative Language Workshop 2",
                      "Day 14: Reading and Connecting",
                      "Day 15: Checkpoint: Thematic Analysis",
                      "Day 16: Analyzing Narrative Structure",
                      "Day 17: Intro to Personal Narratives",
                      "Day 18: Brainstorming Workshop: 'My Own Mango Street'",
                      "Day 19: Narrative Craft: Show, Don't Tell",
                      "Day 20: Drafting the Personal Narrative",
                      "Day 21: Peer Review Workshop 1",
                      "Day 22: Revision Workshop: Voice and Tone",
                      "Day 23: Connecting Texts: Poetry of Identity",
                      "Day 24: Comparative Discussion",
                      "Day 25: Peer Review Workshop 2",
                      "Day 26: Revision Workshop: Polishing the Narrative",
                      "Day 27: Publishing and Sharing",
                      "Day 28: Connecting Texts: Non-fiction",
                      "Day 29: Synthesizing Ideas",
                      "Day 30: Summative Task Intro: Thematic Essay",
                      "Day 31: Essay Workshop: Developing a Thesis",
                      "Day 32: Essay Workshop: Gathering Evidence",
                      "Day 33: Essay Workshop: Outlining",
                      "Day 34: Drafting the Essay: Introduction",
                      "Day 35: Drafting the Essay: Body Paragraphs",
                      "Day 36: Drafting the Essay: Conclusion",
                      "Day 37: Self-Revision Workshop",
                      "Day 38: Peer Review Essay Workshop",
                      "Day 39: Final Revisions and Editing",
                      "Day 40: Final Essay Due. Socratic Seminar Prep",
                      "Day 41: Unit Closure: Socratic Seminar",
                      "Day 42: Creative Response to Text",
                      "Day 43: Gallery Walk and Sharing",
                      "Day 44: Unit Reflection",
                      "Day 45: Portfolio Review and Goal Setting"
                  ]
              }
          }
      },
      "Unit 2: The Power of Persuasion": {
          topics: {
              "Deconstructing Arguments": {
                  lessons: [
                      "Day 1: Unit Introduction: What is Persuasion?",
                      "Day 2: Engage: Analyzing Advertisements",
                      "Day 3: Introduction to Rhetoric: Ethos, Pathos, Logos",
                      "Day 4: Identifying Appeals in Speeches",
                      "Day 5: Anchor Text Introduction",
                      "Day 6: Delineating an Argument",
                      "Day 7: Evaluating Evidence",
                      "Day 8: Analyzing Word Choice and Tone",
                      "Day 9: Rhetorical Devices Workshop",
                      "Day 10: Writing Workshop: Rhetorical Analysis Paragraph",
                      "Day 11: Author's Purpose and Point of View",
                      "Day 12: Reading a Counter-Argument",
                      "Day 13: Comparative Analysis",
                      "Day 14: Introduction to Logical Fallacies",
                      "Day 15: Identifying Fallacies in Media",
                      "Day 16: Evaluating Speaker's Reasoning",
                      "Day 17: Integrating Information from Diverse Media",
                      "Day 18: Debate Preparation",
                      "Day 19: Class Debate",
                      "Day 20: Debate Reflection",
                      "Day 21: Argumentative Writing Intro",
                      "Day 22: Topic Selection and Brainstorming",
                      "Day 23: Research Workshop 1: Formulating Questions",
                      "Day 24: Research Workshop 2: Finding Credible Sources",
                      "Day 25: Writing Workshop: Crafting a Thesis Statement",
                      "Day 26: Outlining the Argument",
                      "Day 27: Workshop: Acknowledging the Counterclaim",
                      "Day 28: Drafting: Introduction",
                      "Day 29: Drafting: Body Paragraphs with Evidence",
                      "Day 30: Drafting: Conclusion",
                      "Day 31: Language for Effect: Academic Vocabulary",
                      "Day 32: Language for Effect: Transitions",
                      "Day 33: Self-Revision Workshop",
                      "Day 34: Peer Review Workshop",
                      "Day 35: Revising Based on Feedback",
                      "Day 36: Editing and Proofreading",
                      "Day 37: Adapting Writing for Presentation",
                      "Day 38: Presentation Workshop: Using Visuals",
                      "Day 39: Presentation Workshop: Delivery",
                      "Day 40: Presentation Rehearsals",
                      "Day 41: Persuasive Presentations Day 1",
                      "Day 42: Persuasive Presentations Day 2",
                      "Day 43: Final Paper Submission",
                      "Day 44: Unit Closure: Socratic Seminar",
                      "Day 45: Unit Reflection"
                  ]
              }
          }
      },
      "Unit 3: Structure and Story": {
          topics: {
              "Analyzing Text Structure and Form": {
                  lessons: [
                      "Day 1: Unit Introduction: What is Narrative Structure?",
                      "Day 2: Engage: Playing with Story",
                      "Day 3: Anchor Text Introduction",
                      "Day 4: Plotting the Story: Freytag's Pyramid",
                      "Day 5: Reading and Mapping the Plot",
                      "Day 6: Structural Elements: Chronological vs. Non-linear",
                      "Day 7: Workshop: Analyzing Foreshadowing",
                      "Day 8: Workshop: Analyzing Flashbacks",
                      "Day 9: Pacing and Tension",
                      "Day 10: Writing Workshop: Structural Analysis Paragraph",
                      "Day 11: Point of View 1: First and Third Person",
                      "Day 12: Point of View 2: Analyzing POV in the Anchor Text",
                      "Day 13: Creative Writing: Shifting Perspectives",
                      "Day 14: Reading and Analyzing Subplots",
                      "Day 15: Discussion: Structure and Theme",
                      "Day 16: Introduction to the Analytical Essay",
                      "Day 17: Essay Workshop: Thesis Development",
                      "Day 18: Essay Workshop: Finding Evidence for Structure",
                      "Day 19: Essay Workshop: Outlining",
                      "Day 20: Drafting the Analytical Essay",
                      "Day 21: Peer Review: Thesis and Introduction",
                      "Day 22: Continued Drafting",
                      "Day 23: Language Workshop: Writing with Precision",
                      "Day 24: Revising for Clarity and Cohesion",
                      "Day 25: Editing and Proofreading",
                      "Day 26: Elaboration Intro: Text to Film Adaptation",
                      "Day 27: Film Viewing Day 1",
                      "Day 28: Film Viewing Day 2",
                      "Day 29: Comparative Analysis: What Changed?",
                      "Day 30: Discussion: The 'Why' of Adaptation",
                      "Day 31: Project Intro: Comparative Presentation",
                      "Day 32: Scene Selection and Analysis",
                      "Day 33: Film Scene Analysis",
                      "Day 34: Developing a Comparative Claim",
                      "Day 35: Storyboarding the Presentation",
                      "Day 36: Presentation Workshop: Clear and Logical Reporting",
                      "Day 37: Presentation Workshop: Delivery",
                      "Day 38: Presentation Rehearsals",
                      "Day 39: Submit Analytical Essay",
                      "Day 40: Presentations Day 1",
                      "Day 41: Presentations Day 2",
                      "Day 42: Presentations Day 3",
                      "Day 43: Unit Closure: Socratic Seminar",
                      "Day 44: Creative Response",
                      "Day 45: Unit Reflection"
                  ]
              }
          }
      },
      "Unit 4: Research and Inquiry": {
          topics: {
              "The Research Process": {
                  lessons: [
                      "Day 1: Unit Introduction: The Power of Inquiry",
                      "Day 2: Engage: Sparking Curiosity",
                      "Day 3: From Broad Topic to Focused Question",
                      "Day 4: Keywords and Search Strategies",
                      "Day 5: Library/Database Orientation",
                      "Day 6: Source Evaluation 1: The CRAAP Test",
                      "Day 7: Source Evaluation 2: Primary vs. Secondary Sources",
                      "Day 8: Assessing Usefulness of Sources",
                      "Day 9: Research Check-in and Question Refinement",
                      "Day 10: Introduction to the Annotated Bibliography",
                      "Day 11: Note-Taking Strategies 1: Paraphrasing",
                      "Day 12: Note-Taking Strategies 2: Summarizing",
                      "Day 13: Note-Taking Strategies 3: Direct Quotation",
                      "Day 14: Avoiding Plagiarism",
                      "Day 15: Citation Workshop 1: MLA Basics",
                      "Day 16: Writing Annotations",
                      "Day 17: Peer Review: Annotated Bibliography",
                      "Day 18: Annotated Bibliography Due",
                      "Day 19: Synthesizing Information: Finding Connections",
                      "Day 20: Developing a Working Thesis",
                      "Day 21: Outlining the Research Paper",
                      "Day 22: Drafting the Introduction",
                      "Day 23: Drafting Body Paragraphs with Synthesis",
                      "Day 24: Workshop: Integrating Quotations",
                      "Day 25: Drafting the Conclusion",
                      "Day 26: Self-Revision Workshop",
                      "Day 27: Peer Review Workshop: Research Paper",
                      "Day 28: Revising Based on Feedback",
                      "Day 29: Citation Workshop 2: Works Cited Page",
                      "Day 30: Final Editing and Proofreading",
                      "Day 31: Research Paper Due",
                      "Day 32: From Paper to Presentation",
                      "Day 33: Presentation Storyboarding",
                      "Day 34: Workshop: Effective Visual Aids",
                      "Day 35: Creating Visuals",
                      "Day 36: Presentation Delivery Workshop",
                      "Day 37: Presentation Rehearsal Day 1",
                      "Day 38: Presentation Rehearsal Day 2",
                      "Day 39: Research Symposium Day 1",
                      "Day 40: Research Symposium Day 2",
                      "Day 41: Research Symposium Day 3",
                      "Day 42: Research Symposium Day 4",
                      "Day 43: Evaluating Texts and Research",
                      "Day 44: Unit Closure: What Have We Learned?",
                      "Day 45: Unit Reflection"
                  ]
              }
          }
      }
    }
  };
