
export const ela9Curriculum = {
    units: {
        "Unit 1: Journeys of Identity": {
            topics: {
                "Analyzing Narrative and Character": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: What is Identity?", standard: "9-10SL1" },
                        { title: "Day 2: Engage: Identity Mapping", standard: "9-10W4" },
                        { title: "Day 3: Anchor Text Introduction", standard: "9-10R2" },
                        { title: "Day 4: Close Reading & Annotation Practice", standard: "9-10R1" },
                        { title: "Day 5: Discussion: First Impressions", standard: "9-10SL1c" },
                        { title: "Day 6: Citing Textual Evidence", standard: "9-10R1" },
                        { title: "Day 7: Figurative Language Workshop 1", standard: "9-10R4" },
                        { title: "Day 8: Analyzing Character Voice", standard: "9-10R3" },
                        { title: "Day 9: Reading for Thematic Development", standard: "9-10R2" },
                        { title: "Day 10: Writing Workshop: Claim-Evidence-Reasoning", standard: "9-10W1" },
                        { title: "Day 11: Thematic Analysis: Shame and Hope", standard: "9-10R2" },
                        { title: "Day 12: Group Discussion: Thematic Patterns", standard: "9-10SL1" },
                        { title: "Day 13: Figurative Language Workshop 2", standard: "9-10L5a" },
                        { title: "Day 14: Reading and Connecting", standard: "9-10R9" },
                        { title: "Day 15: Checkpoint: Thematic Analysis", standard: "9-10W2" },
                        { title: "Day 16: Analyzing Narrative Structure", standard: "9-10R5" },
                        { title: "Day 17: Intro to Personal Narratives", standard: "9-10W3" },
                        { title: "Day 18: Brainstorming Workshop: 'My Own Mango Street'", standard: "9-10W3a" },
                        { title: "Day 19: Narrative Craft: Show, Don't Tell", standard: "9-10W3d" },
                        { title: "Day 20: Drafting the Personal Narrative", standard: "9-10W3" },
                        { title: "Day 21: Peer Review Workshop 1", standard: "9-10W3" },
                        { title: "Day 22: Revision Workshop: Voice and Tone", standard: "9-10W3" },
                        { title: "Day 23: Connecting Texts: Poetry of Identity", standard: "9-10R9" },
                        { title: "Day 24: Comparative Discussion", standard: "9-10SL1" },
                        { title: "Day 25: Peer Review Workshop 2", standard: "9-10W3" },
                        { title: "Day 26: Revision Workshop: Polishing the Narrative", standard: "9-10W3" },
                        { title: "Day 27: Publishing and Sharing", standard: "9-10SL4" },
                        { title: "Day 28: Connecting Texts: Non-fiction", standard: "9-10R9" },
                        { title: "Day 29: Synthesizing Ideas", standard: "9-10W7" },
                        { title: "Day 30: Summative Task Intro: Thematic Essay", standard: "9-10W2" },
                        { title: "Day 31: Essay Workshop: Developing a Thesis", standard: "9-10W2a" },
                        { title: "Day 32: Essay Workshop: Gathering Evidence", standard: "9-10W5" },
                        { title: "Day 33: Essay Workshop: Outlining", standard: "9-10W2a" },
                        { title: "Day 34: Drafting the Essay: Introduction", standard: "9-10W2a" },
                        { title: "Day 35: Drafting the Essay: Body Paragraphs", standard: "9-10W2b" },
                        { title: "Day 36: Drafting the Essay: Conclusion", standard: "9-10W2e" },
                        { title: "Day 37: Self-Revision Workshop", standard: "9-10W2" },
                        { title: "Day 38: Peer Review Essay Workshop", standard: "9-10W2" },
                        { title: "Day 39: Final Revisions and Editing", standard: "9-10L1" },
                        { title: "Day 40: Final Essay Due. Socratic Seminar Prep", standard: "9-10SL1a" },
                        { title: "Day 41: Unit Closure: Socratic Seminar", standard: "9-10SL1" },
                        { title: "Day 42: Creative Response to Text", standard: "9-10W4" },
                        { title: "Day 43: Gallery Walk and Sharing", standard: "9-10SL4" },
                        { title: "Day 44: Unit Reflection", standard: "9-10W4" },
                        { title: "Day 45: Portfolio Review and Goal Setting", standard: "9-10W6" }
                    ]
                }
            }
        },
        "Unit 2: The Power of Persuasion": {
            topics: {
                "Deconstructing Arguments": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: What is Persuasion?", standard: "9-10SL3" },
                        { title: "Day 2: Engage: Analyzing Advertisements", standard: "9-10R8" },
                        { title: "Day 3: Introduction to Rhetoric: Ethos, Pathos, Logos", standard: "9-10R6" },
                        { title: "Day 4: Identifying Appeals in Speeches", standard: "9-10SL3" },
                        { title: "Day 5: Anchor Text Introduction", standard: "9-10R8" },
                        { title: "Day 6: Delineating an Argument", standard: "9-10R8" },
                        { title: "Day 7: Evaluating Evidence", standard: "9-10R8" },
                        { title: "Day 8: Analyzing Word Choice and Tone", standard: "9-10R4" },
                        { title: "Day 9: Rhetorical Devices Workshop", standard: "9-10R6" },
                        { title: "Day 10: Writing Workshop: Rhetorical Analysis Paragraph", standard: "9-10W2" },
                        { title: "Day 11: Author's Purpose and Point of View", standard: "9-10R6" },
                        { title: "Day 12: Reading a Counter-Argument", standard: "9-10R8" },
                        { title: "Day 13: Comparative Analysis", standard: "9-10R9" },
                        { title: "Day 14: Introduction to Logical Fallacies", standard: "9-10R8" },
                        { title: "Day 15: Identifying Fallacies in Media", standard: "9-10R7" },
                        { title: "Day 16: Evaluating Speaker's Reasoning", standard: "9-10SL3" },
                        { title: "Day 17: Integrating Information from Diverse Media", standard: "9-10SL2" },
                        { title: "Day 18: Debate Preparation", standard: "9-10SL4" },
                        { title: "Day 19: Class Debate", standard: "9-10SL1" },
                        { title: "Day 20: Debate Reflection", standard: "9-10W4" },
                        { title: "Day 21: Argumentative Writing Intro", standard: "9-10W1" },
                        { title: "Day 22: Topic Selection and Brainstorming", standard: "9-10W6" },
                        { title: "Day 23: Research Workshop 1: Formulating Questions", standard: "9-10W6" },
                        { title: "Day 24: Research Workshop 2: Finding Credible Sources", standard: "9-10W7" },
                        { title: "Day 25: Writing Workshop: Crafting a Thesis Statement", standard: "9-10W1a" },
                        { title: "Day 26: Outlining the Argument", standard: "9-10W1a" },
                        { title: "Day 27: Workshop: Acknowledging the Counterclaim", standard: "9-10W1a" },
                        { title: "Day 28: Drafting: Introduction", standard: "9-10W1a" },
                        { title: "Day 29: Drafting: Body Paragraphs with Evidence", standard: "9-10W1b" },
                        { title: "Day 30: Drafting: Conclusion", standard: "9-10W1e" },
                        { title: "Day 31: Language for Effect: Academic Vocabulary", standard: "9-10L6" },
                        { title: "Day 32: Language for Effect: Transitions", standard: "9-10W1d" },
                        { title: "Day 33: Self-Revision Workshop", standard: "9-10W1" },
                        { title: "Day 34: Peer Review Workshop", standard: "9-10W1" },
                        { title: "Day 35: Revising Based on Feedback", standard: "9-10W1" },
                        { title: "Day 36: Editing and Proofreading", standard: "9-10L2" },
                        { title: "Day 37: Adapting Writing for Presentation", standard: "9-10SL4" },
                        { title: "Day 38: Presentation Workshop: Using Visuals", standard: "9-10SL5" },
                        { title: "Day 39: Presentation Workshop: Delivery", standard: "9-10SL6" },
                        { title: "Day 40: Presentation Rehearsals", standard: "9-10SL1" },
                        { title: "Day 41: Persuasive Presentations Day 1", standard: "9-10SL4" },
                        { title: "Day 42: Persuasive Presentations Day 2", standard: "9-10SL4" },
                        { title: "Day 43: Final Paper Submission", standard: "9-10W1" },
                        { title: "Day 44: Unit Closure: Socratic Seminar", standard: "9-10SL1d" },
                        { title: "Day 45: Unit Reflection", standard: "9-10W4" }
                    ]
                }
            }
        },
        "Unit 3: Structure and Story": {
            topics: {
                "Analyzing Text Structure and Form": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: What is Narrative Structure?", standard: "9-10R5" },
                        { title: "Day 2: Engage: Playing with Story", standard: "9-10W3" },
                        { title: "Day 3: Anchor Text Introduction", standard: "9-10R5" },
                        { title: "Day 4: Plotting the Story: Freytag's Pyramid", standard: "9-10R3" },
                        { title: "Day 5: Reading and Mapping the Plot", standard: "9-10R3" },
                        { title: "Day 6: Structural Elements: Chronological vs. Non-linear", standard: "9-10R5" },
                        { title: "Day 7: Workshop: Analyzing Foreshadowing", standard: "9-10R5" },
                        { title: "Day 8: Workshop: Analyzing Flashbacks", standard: "9-10R5" },
                        { title: "Day 9: Pacing and Tension", standard: "9-10R3" },
                        { title: "Day 10: Writing Workshop: Structural Analysis Paragraph", standard: "9-10W2" },
                        { title: "Day 11: Point of View 1: First and Third Person", standard: "9-10R6" },
                        { title: "Day 12: Point of View 2: Analyzing POV in the Anchor Text", standard: "9-10R6" },
                        { title: "Day 13: Creative Writing: Shifting Perspectives", standard: "9-10W3a" },
                        { title: "Day 14: Reading and Analyzing Subplots", standard: "9-10R5" },
                        { title: "Day 15: Discussion: Structure and Theme", standard: "9-10SL1" },
                        { title: "Day 16: Introduction to the Analytical Essay", standard: "9-10W2" },
                        { title: "Day 17: Essay Workshop: Thesis Development", standard: "9-10W2a" },
                        { title: "Day 18: Essay Workshop: Finding Evidence for Structure", standard: "9-10W5" },
                        { title: "Day 19: Essay Workshop: Outlining", standard: "9-10W2a" },
                        { title: "Day 20: Drafting the Analytical Essay", standard: "9-10W2" },
                        { title: "Day 21: Peer Review: Thesis and Introduction", standard: "9-10W2" },
                        { title: "Day 22: Continued Drafting", standard: "9-10W2" },
                        { title: "Day 23: Language Workshop: Writing with Precision", standard: "9-10L3" },
                        { title: "Day 24: Revising for Clarity and Cohesion", standard: "9-10W2d" },
                        { title: "Day 25: Editing and Proofreading", standard: "9-10L2" },
                        { title: "Day 26: Elaboration Intro: Text to Film Adaptation", standard: "9-10R7" },
                        { title: "Day 27: Film Viewing Day 1", standard: "9-10R7" },
                        { title: "Day 28: Film Viewing Day 2", standard: "9-10R7" },
                        { title: "Day 29: Comparative Analysis: What Changed?", standard: "9-10R7" },
                        { title: "Day 30: Discussion: The 'Why' of Adaptation", standard: "9-10SL1" },
                        { title: "Day 31: Project Intro: Comparative Presentation", standard: "9-10SL4" },
                        { title: "Day 32: Scene Selection and Analysis", standard: "9-10R7" },
                        { title: "Day 33: Film Scene Analysis", standard: "9-10R7" },
                        { title: "Day 34: Developing a Comparative Claim", standard: "9-10SL4" },
                        { title: "Day 35: Storyboarding the Presentation", standard: "9-10SL5" },
                        { title: "Day 36: Presentation Workshop: Clear and Logical Reporting", standard: "9-10SL4" },
                        { title: "Day 37: Presentation Workshop: Delivery", standard: "9-10SL6" },
                        { title: "Day 38: Presentation Rehearsals", standard: "9-10SL1" },
                        { title: "Day 39: Submit Analytical Essay", standard: "9-10W2" },
                        { title: "Day 40: Presentations Day 1", standard: "9-10SL4" },
                        { title: "Day 41: Presentations Day 2", standard: "9-10SL4" },
                        { title: "Day 42: Presentations Day 3", standard: "9-10SL4" },
                        { title: "Day 43: Unit Closure: Socratic Seminar", standard: "9-10SL1d" },
                        { title: "Day 44: Creative Response", standard: "9-10W4" },
                        { title: "Day 45: Unit Reflection", standard: "9-10W4" }
                    ]
                }
            }
        },
        "Unit 4: Research and Inquiry": {
            topics: {
                "The Research Process": {
                    lessons: [
                        { title: "Day 1: Unit Introduction: The Power of Inquiry", standard: "9-10W6" },
                        { title: "Day 2: Engage: Sparking Curiosity", standard: "9-10SL1" },
                        { title: "Day 3: From Broad Topic to Focused Question", standard: "9-10W6" },
                        { title: "Day 4: Keywords and Search Strategies", standard: "9-10W7" },
                        { title: "Day 5: Library/Database Orientation", standard: "9-10W7" },
                        { title: "Day 6: Source Evaluation 1: The CRAAP Test", standard: "9-10W7" },
                        { title: "Day 7: Source Evaluation 2: Primary vs. Secondary Sources", standard: "9-10R6" },
                        { title: "Day 8: Assessing Usefulness of Sources", standard: "9-10W7" },
                        { title: "Day 9: Research Check-in and Question Refinement", standard: "9-10W6" },
                        { title: "Day 10: Introduction to the Annotated Bibliography", standard: "9-10W7" },
                        { title: "Day 11: Note-Taking Strategies 1: Paraphrasing", standard: "9-10W7" },
                        { title: "Day 12: Note-Taking Strategies 2: Summarizing", standard: "9-10R2" },
                        { title: "Day 13: Note-Taking Strategies 3: Direct Quotation", standard: "9-10W7" },
                        { title: "Day 14: Avoiding Plagiarism", standard: "9-10W7" },
                        { title: "Day 15: Citation Workshop 1: MLA Basics", standard: "9-10W7" },
                        { title: "Day 16: Writing Annotations", standard: "9-10W2" },
                        { title: "Day 17: Peer Review: Annotated Bibliography", standard: "9-10W2" },
                        { title: "Day 18: Annotated Bibliography Due", standard: "9-10W7" },
                        { title: "Day 19: Synthesizing Information: Finding Connections", standard: "9-10W6" },
                        { title: "Day 20: Developing a Working Thesis", standard: "9-10W2a" },
                        { title: "Day 21: Outlining the Research Paper", standard: "9-10W2a" },
                        { title: "Day 22: Drafting the Introduction", standard: "9-10W2a" },
                        { title: "Day 23: Drafting Body Paragraphs with Synthesis", standard: "9-10W2b" },
                        { title: "Day 24: Workshop: Integrating Quotations", standard: "9-10W2b" },
                        { title: "Day 25: Drafting the Conclusion", standard: "9-10W2e" },
                        { title: "Day 26: Self-Revision Workshop", standard: "9-10W2" },
                        { title: "Day 27: Peer Review Workshop: Research Paper", standard: "9-10W2" },
                        { title: "Day 28: Revising Based on Feedback", standard: "9-10W2" },
                        { title: "Day 29: Citation Workshop 2: Works Cited Page", standard: "9-10W7" },
                        { title: "Day 30: Final Editing and Proofreading", standard: "9-10L2" },
                        { title: "Day 31: Research Paper Due", standard: "9-10W2" },
                        { title: "Day 32: From Paper to Presentation", standard: "9-10SL4" },
                        { title: "Day 33: Presentation Storyboarding", standard: "9-10SL5" },
                        { title: "Day 34: Workshop: Effective Visual Aids", standard: "9-10SL5" },
                        { title: "Day 35: Creating Visuals", standard: "9-10SL5" },
                        { title: "Day 36: Presentation Delivery Workshop", standard: "9-10SL6" },
                        { title: "Day 37: Presentation Rehearsal Day 1", standard: "9-10SL1" },
                        { title: "Day 38: Presentation Rehearsal Day 2", standard: "9-10SL1" },
                        { title: "Day 39: Research Symposium Day 1", standard: "9-10SL4" },
                        { title: "Day 40: Research Symposium Day 2", standard: "9-10SL4" },
                        { title: "Day 41: Research Symposium Day 3", standard: "9-10SL4" },
                        { title: "Day 42: Research Symposium Day 4", standard: "9-10SL4" },
                        { title: "Day 43: Evaluating Texts and Research", standard: "9-10R8" },
                        { title: "Day 44: Unit Closure: What Have We Learned?", standard: "9-10SL1d" },
                        { title: "Day 45: Unit Reflection", standard: "9-10W4" }
                    ]
                }
            }
        }
    }
  };
