
'use client';

import React, { useRef } from 'react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Printer, Download, FileDown } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { ScrollArea } from '../ui/scroll-area';
import type { GeneratedContent } from '../generators/NVBiologyGenerator';
import jsPDF from 'jspdf';
import { htmlToText } from 'html-to-text';
import StyledContentDisplay from './StyledContentDisplay';

type CollapsibleSectionProps = {
  title: string;
  children: React.ReactNode;
  contentItem: GeneratedContent;
};

export default function CollapsibleSection({ title, children, contentItem }: CollapsibleSectionProps) {
    const { toast } = useToast();
    const contentRef = useRef<HTMLDivElement>(null);
    const printableContentRef = useRef<HTMLDivElement>(null);

    const getPrintableHTML = (element: HTMLElement) => {
        const headerHtml = `
            <div style="padding-bottom: 20px; border-bottom: 1px solid #ccc; margin-bottom: 20px; text-align: center;">
                <h2 style="font-family: sans-serif; color: #333;">${title} - Created by EduAiGen</h2>
            </div>
        `;
        const footerHtml = `
            <div style="padding-top: 20px; border-top: 1px solid #ccc; margin-top: 20px; text-align: center; font-size: 10px; font-family: sans-serif; color: #666;">
                <p>© ${new Date().getFullYear()} EduAiGen. All Rights Reserved.</p>
                <p>
                    Disclaimer: All lesson plans, tests, lab activities, and other materials generated by EduAiGen are the intellectual property of EduAiGen. These materials are provided for educational, non-commercial use only. They may not be sold, redistributed, or used for any commercial purposes without explicit written permission from EduAiGen.
                </p>
            </div>
        `;
        return headerHtml + element.innerHTML + footerHtml;
    }

    const handlePrint = () => {
        const printableContent = printableContentRef.current;
        if (printableContent) {
            const printWindow = window.open('', '', 'height=800,width=1000');
            if (printWindow) {
                printWindow.document.write('<html><head><title>EduAiGen Document</title>');
                const styles = Array.from(document.styleSheets)
                    .map(styleSheet => {
                        try {
                            if (styleSheet.href) {
                                return `<link rel="stylesheet" href="${styleSheet.href}">`;
                            }
                            return `<style>${Array.from(styleSheet.cssRules).map(rule => rule.cssText).join('')}</style>`;
                        } catch (e) {
                            if (styleSheet.href) {
                                return `<link rel="stylesheet" href="${styleSheet.href}">`;
                            }
                            return '';
                        }
                    })
                    .join('\n');

                printWindow.document.write(styles);
                printWindow.document.write(`
                  <style>
                    @page {
                      size: auto;
                      margin: 2rem;
                    }
                    body { 
                      -webkit-print-color-adjust: exact; 
                      padding: 2rem;
                    } 
                    .document-view h2, .document-view h3, .document-view h4 { 
                      color: #333 !important; 
                    }
                  </style>
                `);
                printWindow.document.write('</head><body>');
                printWindow.document.write(getPrintableHTML(printableContent));
                printWindow.document.write('</body></html>');
                printWindow.document.close();
                setTimeout(() => {
                    printWindow.print();
                    printWindow.close();
                }, 250); 
            }
        }
    };

    const handleDownloadDoc = () => {
        const content = printableContentRef.current;
        if (!content) return;

        toast({
            title: 'Generating .doc file...',
            description: 'Please wait while we prepare your document.',
        });

        const htmlContent = getPrintableHTML(content);

        const blob = new Blob(['<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>' + htmlContent + '</body></html>'], {
            type: 'application/msword'
        });

        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${title.replace(/ /g, '_')}.doc`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const handleDownloadPdf = async () => {
        const input = printableContentRef.current;
        if (!input) return;

        toast({
            title: 'Generating PDF...',
            description: 'Please wait while we create your document.',
        });

        try {
            const pdf = new jsPDF('p', 'pt', 'a4');
            const source = `
                <div style="font-family: Helvetica, Arial, sans-serif; font-size: 12px;">
                    ${getPrintableHTML(input)}
                </div>
            `;
            
            await pdf.html(source, {
                callback: function (doc) {
                    doc.save(`${title.replace(/ /g, '_')}.pdf`);
                },
                x: 15,
                y: 15,
                width: 550,
                windowWidth: input.scrollWidth,
                autoPaging: 'text',
            });

        } catch (error) {
            console.error('Error generating PDF:', error);
            toast({
                title: 'PDF Generation Failed',
                description: 'Could not generate the PDF file. Please try again.',
                variant: 'destructive',
            });
        }
    };
      
  return (
    <Card className="mt-6 shadow-md">
      <div style={{ display: 'none' }}>
        <div ref={printableContentRef} id={`printable-content-${contentItem.id}`} className="p-4 bg-white text-black">
             <StyledContentDisplay content={contentItem.content} type={contentItem.type} />
        </div>
      </div>
      <Accordion type="single" collapsible defaultValue="item-1">
        <AccordionItem value="item-1" className="border-b-0">
            <CardHeader className="flex flex-row items-center justify-between p-4 flex-wrap gap-4">
                <AccordionTrigger className="flex-1 text-left hover:no-underline p-0">
                    <h3 className="text-xl font-headline">{title}</h3>
                </AccordionTrigger>
                <div className="flex items-center gap-2 ml-4 flex-wrap">
                    <Button variant="outline" size="icon" onClick={handlePrint} title="Print">
                        <Printer className="h-4 w-4" />
                        <span className="sr-only">Print</span>
                    </Button>
                    <Button variant="outline" size="icon" onClick={handleDownloadPdf} title="Download as PDF">
                        <Download className="h-4 w-4" />
                        <span className="sr-only">Download as PDF</span>
                    </Button>
                    <Button variant="outline" size="icon" onClick={handleDownloadDoc} title="Download as .doc">
                        <FileDown className="h-4 w-4" />
                        <span className="sr-only">Download as .doc</span>
                    </Button>
                </div>
            </CardHeader>
            <AccordionContent>
                <CardContent className="p-0">
                    <ScrollArea className="max-h-[800px] overflow-y-auto">
                        <div ref={contentRef} id={`content-${contentItem.id}`} className="p-4">{children}</div>
                    </ScrollArea>
                </CardContent>
            </AccordionContent>
        </AccordionItem>
      </Accordion>
    </Card>
  );
}
