
'use client';

import React from 'react';
import { useAuth } from '@/context/AuthContext';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Button } from '../ui/button';

export default function DisclaimerDialog() {
  const { showDisclaimer, agreeToDisclaimer } = useAuth();

  const handleAgree = () => {
    agreeToDisclaimer();
  };

  return (
    <AlertDialog open={showDisclaimer}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Terms of Use & Disclaimer</AlertDialogTitle>
          <AlertDialogDescription className="space-y-4 pt-4 text-left">
            <p>
              Welcome to EduAiGen! Before you proceed, please read and agree to the following terms:
            </p>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                <strong>Non-Commercial Use:</strong> All lesson plans, tests, lab activities, and other materials generated by EduAiGen are the intellectual property of EduAiGen. These materials are provided for your personal, educational, and non-commercial use only. They may not be sold, redistributed, or used for any commercial purposes without explicit written permission from EduAiGen.
              </li>
              <li>
                <strong>Accuracy and Review:</strong> As an AI-powered tool, all generated content must be carefully examined for accuracy and appropriateness by a qualified educator before use. You are responsible for the final content used in your educational setting.
              </li>
              <li>
                <strong>Feedback for Improvement:</strong> You agree to report any issues, inaccuracies, or concerns with generated content to help us improve our AI models. Please contact us at <a href="mailto:admin@eduaigen.org" className="underline text-primary">admin@eduaigen.org</a> to report issues.
              </li>
            </ul>
            <p>
              By clicking "I Agree," you acknowledge that you have read, understood, and agreed to these terms.
            </p>
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogAction asChild>
            <Button onClick={handleAgree}>I Agree</Button>
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
